<style>
#sideBareMenuGaucheSecretariat{ visibility: hidden }

#sideBareMenuGaucheSecretariat{ min-width:200px; max-width: 430px;}
</style>

<script>
$(window).load(function () {

	$('#waitMenuGaucheSecretariat').toggle(false);
	$('#sideBareMenuGaucheSecretariat').fadeIn().css({'visibility':'visible'});
	 
});
</script>

<div id="waitMenuGaucheSecretariat" style="color: #cccccc; font-size: 13px;  margin-top: 80px;  margin-left: 60px;" > <span> Chargement ... </span> </div>


<ul id="sideBareMenuGaucheSecretariat">
	<!-- MENU ***DOSSIER PATIENT*** -->
	<li id="dossier_patient"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Dossier patient </span></a> </li>

	<li id="plus_dossier_patient" style="background: #4a5765;" >

	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/secretariat/ajouter-patient";?>"  >
	       <span id="nouveau_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.png'?>' alt='Liste' /> Nouveau</span></a>
	   </div>

	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/secretariat/liste-patient";?>">
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.png'?>' alt='Liste' />
	       <span id="liste_dossier_patient_style" style="font-size:15px; color: white; font-family:Times New Roman;">Liste</span></a>
	   </div>
	</li>

	<!-- MENU ***ANALYSES*** -->
	<li id="analyses"><a href="">
	   <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Analyses </span></a> 
	</li>

	<li id="plus_analyses" style="background: #4a5765;" >

	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/secretariat/demandes-analyses";?>"  >
	      <span id="analyses_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.png'?>' alt='Liste' /> Demandes</span></a>
	   </div>

	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/secretariat/liste-demandes";?>">
	      <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.png'?>' alt='Liste' />
	      <span id="liste_analyses_style" style="font-size:15px; color: white; font-family:Times New Roman;">Liste des demandes</span></a>
	   </div>
	   
	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/secretariat/liste-resultats";?>">
	      <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.png'?>' alt='Liste' />
	      <span id="liste_acte_style" style="font-size:15px; color: white; font-family:Times New Roman;">Liste des r&eacute;sultats</span></a>
	   </div>
	   
	   <div id="listeAnalysesNonConformes" style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/secretariat/liste-non-conforme";?>" >
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/warning_16.png'?>' />
	       <span id="liste_nonconforme_style_infirm" style="font-size:15px; color: white; font-family:Times New Roman;">Non conformit&eacute;</span></a>
	   </div>
	   
	</li>

</ul>


<?php
//CHOISIR LE MENU A AFFICHER SELON QUE C'EST LE MEDECIN OU LE SURVEILLANT
$user = $this->layout()->user;
$role = $user['role'];

$nonConformite = $this->layout()->nonConformite;
if(!$nonConformite){ ?>
<script> $('#listeAnalysesNonConformes').toggle(false); </script>
<?php } ?>


<script>
var base_url = window.location.toString();
var tabUrl = base_url.split("public");

//*******************************************************************************************************************************
//ADMISSION
function dep_analyses1(){
	$('#analyses').click(function(){
		$("#analyses").replaceWith("<li id='analyses'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/plus-green1.png' alt='Liste' /> Analyses </span></a></li>");
		dep_analyses2();
	    $('#plus_analyses').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_analyses2(){
	$('#analyses').click(function(){
		$("#analyses").replaceWith("<li id='analyses' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Analyses </span></a></li>");
		dep_analyses1();
	    $('#plus_analyses').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_analyses').toggle(false);
$('#analyses').click(function(){
	$("#analyses").replaceWith("<li id='analyses' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Analyses </span></a></li>");
	dep_analyses1();
$('#plus_analyses').animate({
    height : 'toggle'
},1000);
return false;
});


//*******************************************************************************************************************************
//DOSSIER PATIENT
function dep_dossier_patient1(){
	$('#dossier_patient').click(function(){
		$("#dossier_patient").replaceWith("<li id='dossier_patient'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/plus-green1.png' alt='Liste' /> Dossier patient </span></a></li>");
		dep_dossier_patient2();
	    $('#plus_dossier_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_dossier_patient2(){
	$('#dossier_patient').click(function(){
		$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Dossier patient </span></a></li>");
		dep_dossier_patient1();
	    $('#plus_dossier_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_dossier_patient').toggle(false);
$('#dossier_patient').click(function(){
	$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Dossier patient </span></a></li>");
	dep_dossier_patient1();
$('#plus_dossier_patient').animate({
height : 'toggle'
},1000);
return false;
});

</script>

