<script>
//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_menu_statistiques').toggle(true);
$("#menu_statistiques").replaceWith("<li id='menu_statistiques' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='<?php echo $this->basePath().'/images_icons/moin-green2.PNG';?>'  /> Statistiques </span></a></li>");
dep_menu_statistiques1();
$('#menu_statistiques_style').css({'font-weight':'bold','color':'white','font-size':'21px'});
</script>

<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/consultation/styleListeConsultations.css');?>
<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/jqueryCharts/jquery.canvasjs.min.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/facturation/informationsStatistiques.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/zingchart/zingchart.min.js');?>
    		        


<!-- JS & CSS de anychart -->  
<!-- JS & CSS de anychart -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/anychart/js/anychart-base.min.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/anychart/js/anychart-ui.min.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/anychart/js/anychart-cartesian-3d.min.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/anychart/js/anychart-exports.min.js');?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/anychart/css/anychart-ui.min.css');?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/anychart/fonts/css/anychart-font.min.css');?>



<?php use Facturation\View\Helper\DateHelper;
$Control = new DateHelper();?>
<style>
#contenuInterface{ visibility: hidden; }
</style>

<script>
$(window).load(function () {
	setTimeout(function(){
		$('#wait').toggle(false);
		$('#contenuInterface').fadeIn().css({'visibility':'visible'}); 
	});
});
</script>


<div id="titre" style='font-family: police2; text-decoration:none; color: green; font-size: 18px; font-weight: bold; padding-left: 20px;'><iS style='font-size: 25px;'>&curren;</iS> <span id="menu_infos"> MENU </span></div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>
<div id="contenuInterface" >


<!-- LA PREMIERE PAGE POUR INFOS 1 -->
<!-- LA PREMIERE PAGE POUR INFOS 1 -->
<!-- LA PREMIERE PAGE POUR INFOS 1 -->
<div id="contenuPageA" >


    <script type="text/javascript"> 
    
     var ordonnees = [];
     var abcisses  = [];
     var i = 1;
     var j = 1;

     <?php 
       $formeGraves = count($this->typagesPatientsInternes[0]);
   	   for($i = 0 ; $i < count($this->typagesPatientsInternes[0]) ; $i++){
   	     $typages = $this->typagesPatientsInternes[0][$i];
   	 ?>
   	     ordonnees [i++] = '<?php echo $typages; ?>';
      	  abcisses [j++] = <?php echo $this->typagesPatientsInternes[1][$typages]; ?>; 

     <?php } ?>

     //===============================================================================
     
     var ordEthnie = [];
     var absEthnie = [];
     var iabsEth = 1;
     var jabsEth = 1;
     <?php 
       for( $i = 0 ; $i < count($this->peresNouveauNesSelonEthnies[0]) ; $i++){ 
       $ethnie = $this->peresNouveauNesSelonEthnies[0][$i];
     ?>
        absEthnie [iabsEth++] = "<?php echo $ethnie;?>";
        ordEthnie [jabsEth++] =  <?php echo $this->peresNouveauNesSelonEthnies[1][$ethnie]; ?>;

     <?php }?>

     //=================================================================================
     
     var ordTypeHemo = [];
     var absTypeHemo = [];
     var iabsTH = 1;
     var jabsTH = 1;
     <?php 
       for( $i = 0 ; $i < count($this->differentsTypesProfils[0]) ; $i++){ 
       $typageHemo = $this->differentsTypesProfils[0][$i];
     ?>
        absTypeHemo [iabsTH++] = "<?php echo $typageHemo;?>";
        ordTypeHemo [jabsTH++] =  <?php echo $this->differentsTypesProfils[1][$typageHemo]; ?>;

     <?php }?>

     //==================================================================================

    </script>
    

    <script >

    var nbPatientD   = <?php echo $this->nbPatientD;   ?> //Nombre de patients depistes
    var nbPatientDN  = <?php echo $this->nbPatientDN;  ?> //Nombre de patients depistes nÈgatifs (externe)
    var nbPatientDP  = <?php echo $this->nbPatientDP;  ?> //Nombre de patients depistes positifs (interne)
    var nbPatientDPF = <?php echo $this->nbPatientDPF; ?> //Nombre de patients depistes positifs (interne) Feminin
    var nbPatientDPM = <?php echo $this->nbPatientDPM; ?> //Nombre de patients depistes positifs (interne) Masculin

    $(document).ready(function($) {

    //Patients depistÈs
    //Patients depistÈs
	function patientsDepistes() {
		var patientsDepistes = new CanvasJS.Chart("patientsDepistes", {
			animationEnabled: true,
			animationDuration: 2000,
			data: [{
				type: "column",
				dataPoints: [

					{ y: nbPatientDN, label: "Externe" },
					{ y: nbPatientDP, label: "Interne" },
				]

			}]

		});
		patientsDepistes.render();
	}
	
	//Patients internes
	//Patients internes
	function patientsInternes() {
		var patientsInternes = new CanvasJS.Chart("patientsInternes", {
			animationEnabled: true,
			animationDuration: 2000,
			data: [{
				type: "pie",
				dataPoints: [

					{ y: nbPatientDPF, label: "Feminin" },
					{ y: nbPatientDPM, label: "Masculin" },
				]

			}]

		});
		patientsInternes.render();
	}


	//Les typages des patients internes
	//Les typages des patients internes
	var Pile = [];
	var PileAnyChart = [];

	for(var k = 1 ; k < ordonnees.length ; k++){
		var tabValeur = { y: abcisses[k], label: ordonnees[k] };
		Pile.push(tabValeur);

		/*-----------------*/
		var valeurCouple = [ordonnees[k],abcisses[k]];
		PileAnyChart.push(valeurCouple);
		/*----------------*/
	}

	function typagePatientsInternes() {
		var typagePatientsInternes = new CanvasJS.Chart("typagePatientsInternes", {

			animationEnabled: true,
			animationDuration: 2000,
			data: [{
				type: "bar",
				dataPoints: Pile
			}]

		});
		typagePatientsInternes.render();
	}



	//La repartition selon les ethnies
	//La repartition selon les ethnies
	var PileEthnie = [];
	var PileEthnieAnyChart = [];

	for(var ke = 1 ; ke < ordEthnie.length ; ke++){ 
		var tabDonnee = { y : ordEthnie[ke] , label : absEthnie[ke] };
		PileEthnie.push(tabDonnee);

		/*-----------------*/
		var valeurCouple = [absEthnie[ke],ordEthnie[ke]];
		PileEthnieAnyChart.push(valeurCouple);
		/*----------------*/
	}

	function repartitionSelonEthnies() {
		var repartitionSelonEthnies = new CanvasJS.Chart("repartitionSelonEthniesPie", {
			data: [{
				type: "pie",
				dataPoints: PileEthnie
			}]

		});
		repartitionSelonEthnies.render();

		var repartitionSelonEthnies = new CanvasJS.Chart("repartitionSelonEthnies", {
			data: [{
				type: "column",
				dataPoints: PileEthnie
			}]

		});
		repartitionSelonEthnies.render();
	}


	//Les diffÈrents types d'hÈmogobine rencontrÈs
	//Les diffÈrents types d'hÈmogobine rencontrÈs
	var PileDiffTypeHemo = [];
	var PileDiffTypeHemoAnyChart = [];

	for(var kh = 1 ; kh < ordTypeHemo.length ; kh++){ 
		var tabDonnees = { y : ordTypeHemo[kh] , label : absTypeHemo[kh] };
		PileDiffTypeHemo.push(tabDonnees);

		/*-----------------*/
		var valeurCouple = [absTypeHemo[kh],ordTypeHemo[kh]];
		PileDiffTypeHemoAnyChart.push(valeurCouple);
		/*----------------*/
	}

	function lesDifferentsTypesHemoglobineRencontres() {
		var lesDifferentsTypesHemoglobineRencontresColumn = new CanvasJS.Chart("lesDifferentsTypesHemoglobineRencontresColumn", {
			data: [{
				type: "column",
				dataPoints: PileDiffTypeHemo
			}]

		});
		lesDifferentsTypesHemoglobineRencontresColumn.render();

		var lesDifferentsTypesHemoglobineRencontresPie = new CanvasJS.Chart("lesDifferentsTypesHemoglobineRencontresPie", {
			data: [{
				type: "pie",
				dataPoints: PileDiffTypeHemo
			}]

		});
		lesDifferentsTypesHemoglobineRencontresPie.render();
	}

	//RÈpartition des diffÈrents types d'hÈmoglobine selon l'ethnie
	//RÈpartition des diffÈrents types d'hÈmoglobine selon l'ethnie


	
	
	/*-- APPEL DES FONCTIONS --*/
	//patientsDepistes();
	//patientsInternes();
	//typagePatientsInternes();
	//repartitionSelonEthnies();
	//lesDifferentsTypesHemoglobineRencontres();


    
    //***************************************************************
    //***************************************************************


	/*Utilisation de AnyChar --- Utilisation de AnyChar*/
	/*Utilisation de AnyChar --- Utilisation de AnyChar*/
	
	//Patients depistÈs
    //Patients depistÈs
	function patientsDepistesAnyChart() {

		anychart.onDocumentReady(function () {
		    // create column chart
		    var chart = anychart.column3d();

		    // turn on chart animation
		    chart.animation(true);

		    // set chart title text settings
		    chart.title('');

		    // create area series with passed data
		    chart.column([
		        ['Externe', nbPatientDN],
		        ['Interne', nbPatientDP],
		    ]);

		    chart.tooltip()
		            .position('center-top')
		            .anchor('center-bottom')
		            .offsetX(0)
		            .offsetY(5)
		            .format('{%Value}');

		    // set scale minimum
		    chart.yScale().minimum(0);

		    // set yAxis labels formatter
		    chart.yAxis().labels().format('{%Value}{groupsSeparator: }');

		    chart.tooltip().positionMode('point');
		    chart.interactivity().hoverMode('by-x');

		    chart.xAxis().title('');
		    chart.yAxis().title('');

		    // set container id for the chart
		    chart.container('patientsDepistes');

		    // initiate chart drawing
		    chart.draw();
		});

	}

	//Patients internes
	//Patients internes
    function patientsInternesAnyChart(){
        
    	anychart.onDocumentReady(function () {
        	
    	    // create pie chart with passed data
    	    var chart = anychart.pie3d([
    	        ['Feminin', nbPatientDPF],
    	        ['Masculin', nbPatientDPM]
    	    ]);

       	    // turn on chart animation
		    chart.animation(true);
		    
    	    // set chart title text settings
    	    chart.title('')
    	    // set chart radius
    	    .radius('43%');

    	    // set container id for the chart
    	    chart.container('patientsInternes');
    	    // initiate chart drawing
    	    chart.draw();
    	});
    }

    //Les typages des patients internes ‡ bar
	//Les typages des patients internes ‡ bar
    function typagePatientsInternesBarAnyChart() {

    	anychart.onDocumentReady(function () {
    	    // create bar chart
    	    var chart = anychart.bar3d();

    	    // turn on chart animation
    	    chart.animation(true);

    	    // set chart padding
    	    chart.padding([10, 40, 5, 20]);

    	    // set chart title text settings
    	    chart.title('');

    	    // create area series with passed data
    	    chart.bar( PileAnyChart );

    	    // set tooltip settings
    	    chart.tooltip()
    	            .positionMode('point')
    	            .format('{%Value}')
    	            .position('right')
    	            .anchor('left-center')
    	            .offsetX(5)
    	            .offsetY(0);

    	    // set yAxis labels formatter (axeY)
    	    chart.yAxis().labels().format('{%Value}');

    	    // set titles for axises
    	    chart.xAxis().title('');
    	    chart.yAxis().title('');
    	    chart.interactivity().hoverMode('by-x');

    	    // set scale minimum
    	    chart.yScale().minimum(0);

    	    // set container id for the chart
    	    chart.container('typagePatientsInternes');

    	    // initiate chart drawing
    	    chart.draw();
    	});

	}


    //Les typages des patients internes ‡ camembert
	//Les typages des patients internes ‡ camembert
    function typagePatientsInternesCamembertAnyChart() {

    	anychart.onDocumentReady(function () {

    		// create pie chart with passed data
    	    var chart = anychart.pie3d( PileAnyChart );

       	    // turn on chart animation
		    chart.animation(true);
		    
    	    // set chart title text settings
    	    chart.title('')
    	    // set chart radius
    	    .radius('43%');

    	    // set container id for the chart
    	    chart.container('typagePatientsInternesAnychartPie');
    	    // initiate chart drawing
    	    chart.draw();
        	
    	});

	}


    //La repartition selon les ethnies
	//La repartition selon les ethnies
	function repartitionSelonEthniesAnyChart() {

		anychart.onDocumentReady(function () {

    		// create pie chart with passed data
    	    var chart = anychart.pie3d( PileEthnieAnyChart );

       	    // turn on chart animation
		    chart.animation(true);
		    
    	    // set chart title text settings
    	    chart.title('')
    	    // set chart radius
    	    .radius('43%');

    	    // set container id for the chart
    	    chart.container('repartitionSelonEthniesPie');
    	    // initiate chart drawing
    	    chart.draw();
        	
    	});

		anychart.onDocumentReady(function () {
		    // create column chart
		    var chart = anychart.column3d();

		    // turn on chart animation
		    chart.animation(true);

		    // set chart title text settings
		    chart.title('');

		    // create area series with passed data
		    chart.column( PileEthnieAnyChart );

		    chart.tooltip()
		            .position('center-top')
		            .anchor('center-bottom')
		            .offsetX(0)
		            .offsetY(5)
		            .format('{%Value}');

		    // set scale minimum
		    chart.yScale().minimum(0);

		    // set yAxis labels formatter
		    chart.yAxis().labels().format('{%Value}{groupsSeparator: }');

		    chart.tooltip().positionMode('point');
		    chart.interactivity().hoverMode('by-x');

		    chart.xAxis().title('');
		    chart.yAxis().title('');

		    // set container id for the chart
		    chart.container('repartitionSelonEthnies');

		    // initiate chart drawing
		    chart.draw();
		});
		
	}



	//Les diffÈrents types d'hÈmogobine rencontrÈs
	//Les diffÈrents types d'hÈmogobine rencontrÈs
	function lesDifferentsTypesHemoglobineRencontresAnyChart() {

		anychart.onDocumentReady(function () {

    		// create pie chart with passed data
    	    var chart = anychart.pie3d( PileDiffTypeHemoAnyChart );

       	    // turn on chart animation
		    chart.animation(true);
		    
    	    // set chart title text settings
    	    chart.title('')
    	    // set chart radius
    	    .radius('43%');

    	    // set container id for the chart
    	    chart.container('lesDifferentsTypesHemoglobineRencontresPie');
    	    // initiate chart drawing
    	    chart.draw();
        	
    	});

		anychart.onDocumentReady(function () {
		    // create column chart
		    var chart = anychart.column3d();

		    // turn on chart animation
		    chart.animation(true);

		    // set chart title text settings
		    chart.title('');

		    // create area series with passed data
		    chart.column( PileDiffTypeHemoAnyChart );

		    chart.tooltip()
		            .position('center-top')
		            .anchor('center-bottom')
		            .offsetX(0)
		            .offsetY(5)
		            .format('{%Value}');

		    // set scale minimum
		    chart.yScale().minimum(0);

		    // set yAxis labels formatter
		    chart.yAxis().labels().format('{%Value}{groupsSeparator: }');

		    chart.tooltip().positionMode('point');
		    chart.interactivity().hoverMode('by-x');

		    chart.xAxis().title('');
		    chart.yAxis().title('');

		    // set container id for the chart
		    chart.container('lesDifferentsTypesHemoglobineRencontresColumn');

		    // initiate chart drawing
		    chart.draw();
		});

	}


    
    
    patientsDepistesAnyChart();
    patientsInternesAnyChart();
    typagePatientsInternesBarAnyChart();
    typagePatientsInternesCamembertAnyChart();
    repartitionSelonEthniesAnyChart();
    lesDifferentsTypesHemoglobineRencontresAnyChart();

	/*=== Utilisation de AnyChar --- Utilisation de AnyChar ===*/
	/*=== Utilisation de AnyChar --- Utilisation de AnyChar ===*/








    
    });

    </script>
	
	
	<table style="width: 100%; height: 20%;">
	
	 <tr style="background: white; width: 100%;"><td colspan="3"> <img id="retourPageAMenuInfos" style="width: 16px;position: absolute; height: 16px; float: left; cursor: pointer; " src='../images_icons/72.png' > <!-- a style='float: right; position: absolute; right: 50px; text-decoration: none;' href="javascript:captureImage();" title=""> &#9775; </a--> </td></tr>
	 <tr style="width: 100%; height: 20%;">
	 
	   <!-- PREMIERE COLONNE -->
	   <!-- PREMIERE COLONNE -->
	   <td style="width: 25%; height: 20%; vertical-align: top;" >
	     <table style="width: 100%;">
	       <tr style="width: 100%; ">
	         <td style="width: 100%; height: 40px; font-family: Goudy Old Style; text-align: center;">
	          <?php echo $this->nbPatientD; ?> patients d√©pist√©s
	         </td>
	       </tr>
	       
	       
           <tr style="width: 100%; ">
	         <td style="width: 100%; height: 40px; font-family: Goudy Old Style; font-weight: normal; font-size: 17px; text-align: center;">
	             <div  align="center" style="overflow-y: auto; margin-right: 5px; margin-bottom: 0px;" >
	              <table style="height: 36px; border: 1px solid #cccccc;">
	                <tr style="height: 18px; border: 1px solid #cccccc;">
	                  <td style=" border: 2px solid #cccccc; padding-left: 6px; padding-right: 6px;"> Externe </td>
	                  <td style=" border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; text-align: right; min-width: 50px;"> <?php echo $this->nbPatientDN; ?> </td>
	                  <?php if( count($this->pourcentageDepister) == 2){ ?>
    	                  <td style=" border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; text-align: right;"> <?php echo $this->pourcentageDepister[0]." %"; ?> </td>
	                  <?php } ?>
	                </tr>
	                <tr style="width: 100%; height: 18px; border: 1px solid #cccccc;">
	                  <td style=" border: 2px solid #cccccc; padding-left: 6px; padding-right: 6px;"> Interne </td>
	                  <td style=" border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; text-align: right; min-width: 50px;"> <?php echo $this->nbPatientDP; ?> </td>
	                  <?php if( count($this->pourcentageDepister) == 2){ ?>
    	                  <td style=" border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; text-align: right;"> <?php echo $this->pourcentageDepister[1]." %"; ?> </td>
	                  <?php } ?>
	                </tr>
	                
	                
	              </table>
	             </div> 
	         </td>
	       </tr>	       
	       
	       
	       <tr style="width: 100%; vertical-align: top;">
	         <td style="width: 100%; height: 400px; vertical-align: top;" align="center">
	           <div id="patientsDepistes" style="height: 400px; width: 100%;"></div>
	         </td>
	       </tr>
	     </table> 
	   </td>
	
	
       <!-- DEUXIEME COLONNE -->
       <!-- DEUXIEME COLONNE -->
	   <td style="width: 25%; height: 20%; vertical-align: top; ">
	     <table style="width: 100%; border-left: 2px solid #cccccc;">
	       <tr style="width: 100%; ">
	         <td style="width: 100%; height: 40px; font-family: Goudy Old Style; text-align: center;">
	          <?php echo $this->nbPatientDP; ?> patients internes
	         </td>
	       </tr>
	       
	       
	       <tr style="width: 100%; ">
	         <td style="width: 100%; height: 40px; font-family: Goudy Old Style; font-weight: normal; font-size: 17px; text-align: center; ">
	             <div  align="center" style="margin-bottom: 15px;">
	              <table style="width: 75%; height: 36px; border: 1px solid #cccccc;">
	                <tr style="width: 100%; height: 18px; border: 1px solid #cccccc;">
	                  <td style="width: 33%; border: 2px solid #cccccc; padding-left: 10px;"> Masculin </td>
	                  <td style="width: 33%; border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; text-align: right;"> <?php echo $this->nbPatientDPM; ?> </td>
	                  <?php if( count($this->pourcentageDepisterPositif) == 2){ ?>
    	                  <td style="width: 33%; border: 2px solid #cccccc; padding-left: 5px; padding-right: 5px; text-align: right;"> <?php echo $this->pourcentageDepisterPositif[0]." %"; ?> </td>
	                  <?php } ?>
	                </tr>
	                <tr style="width: 100%; height: 18px; border: 1px solid #cccccc;">
	                  <td style="width: 33%; border: 2px solid #cccccc; padding-left: 10px;"> F&eacute;minin </td>
	                  <td style="width: 33%; border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; text-align: right;"> <?php echo $this->nbPatientDPF; ?> </td>
	                  <?php if( count($this->pourcentageDepisterPositif) == 2){ ?>
    	                  <td style="width: 33%; border: 2px solid #cccccc; padding-left: 5px; padding-right: 5px; text-align: right;"> <?php echo $this->pourcentageDepisterPositif[1]." % "; ?> </td>
	                  <?php } ?>
	                </tr>
	                
	                
	              </table>
	             </div> 
	         </td>
	       </tr>	       
	       
	       
	       <tr style="width: 100%; vertical-align: top;">
	         <td style="width: 100%; height: 400px;" align="center">
	          <div id="patientsInternes" style="height: 400px;"></div>
	         </td>
	       </tr>
	     </table> 
	   </td>
	   
	   
   	   <!-- TROISIEME COLONNE -->
   	   <!-- TROISIEME COLONNE -->
	   <td style="width: 50%; height: 20%; vertical-align: top;">
	     <table style="width: 100%; border-left: 2px solid #cccccc;">
	       <tr style="width: 100%; ">
	         <td style="width: 100%; height: 40px; font-family: Goudy Old Style; text-align: center;">
	           <?php if (in_array('CC', $this->typagesPatientsInternes[0])){ ?>
	           <?php echo $formeGraves-1; ?> profils de sympt&ocirc;me dr√©panocitaire majeur & un statut CC
	           <?php }else{?>
	           <?php echo $formeGraves ?> profils de sympt&ocirc;me dr√©panocitaire majeur
	           <?php }?>
	         </td>
	       </tr>
	       
	       
	       <tr style="width: 100%; ">
	         <td align="center" style="width: 100%; height: 40px; font-family: Goudy Old Style; font-weight: normal; font-size: 17px; text-align: center;">
	             <div  align="center" style="width: 100%; margin-left: 10px; max-width: 560px; overflow: auto; margin-bottom: 0px;">
	              <table style="height: 36px; border: 1px solid #cccccc;">
	                <tr style="height: 18px; border: 1px solid #cccccc;">
	                  
	                  <?php for( $i = 0 ; $i < count($this->typagesPatientsInternes[0]) ; $i++){ ?>
    	                  <td style="min-width: 80px; border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px;"> <?php echo $this->typagesPatientsInternes[0][$i]; ?> </td>
	                  <?php } ?>
	                
	                </tr>
	                
	                <tr style="height: 18px; border: 1px solid #cccccc;">

	                  <?php for( $i = 0 ; $i < count($this->typagesPatientsInternes[0]) ; $i++){ ?>
    	                  <td style="border: 2px solid #cccccc; padding-left: 10px; text-align: center;"> 
    	                    <span style="font-weight: bold;"><?php echo $this->typagesPatientsInternes[1][$this->typagesPatientsInternes[0][$i]].' '; ?> </span>
    	                    <?php echo ' - {'.$this->pourcentageProfilsPatientsInterne[$i].'%}'; ?>
    	                  </td>
	                  <?php } ?>
	                  
	                </tr>
	                
	                
	              </table>
	             </div> 
	         </td>
	       </tr>	       
	       
	       
	       <tr style="width: 100%; vertical-align: top;">
	         <td style="width: 100%; height: 400px;" align="center">
	           <div id="optionChoixAnyChart"><div class="premEl">1</div> <div class="deuxiemE2" >2</div></div>
	           <div id="typagePatientsInternes" style="height: 400px;"></div>
	           <div id="typagePatientsInternesAnychartPie" style="height: 400px; display: none;" ></div>
	         </td>
	       </tr>
	     </table> 
	   </td>
	 </tr>
	</table>
	
</div>

<!-- LA DEUXIEME PAGE POUR INFOS 2 -->
<!-- LA DEUXIEME PAGE POUR INFOS 2 -->
<!-- LA DEUXIEME PAGE POUR INFOS 2 -->
<div id="contenuPageB" >
    <table style="width: 100%; height: 20%;">
	  <tr style="background: white; width: 100%; vertical-align: top; height: 5px;"><td> <img id="retourPageBMenuInfos" style="width: 16px;position: absolute; height: 16px; float: left; cursor: pointer; " src='../images_icons/72.png' > <!--a style='float: right; position: absolute; right: 50px; text-decoration: none;' href="javascript:captureImage();" title=""> &#9775; </a--> </td></tr>
      
      <tr style="width: 100%; vertical-align: top; background: yello; ">
	    <td align="center" style="width: 100%;">
	      <div style="width: 100%; background: re;">
	        
	        <table style="width: 100%;">
	          <tr style="width: 100%;"> 
	          
	            <!-- PREMIERE COLONNE -->
	            <!-- PREMIERE COLONNE -->
	            <td style="width: 33%; height: 250px; background: indig; text-align: center; border-right: 2px solid #cccccc; vertical-align: top;">
	              
	              <div style="width: 100%; font-family: Goudy Old Style; font-size: 21px; font-weight: normal;"> 
	                  <span style="font-size: 16px; color: green; font-weight: bold;">&#9883;</span> nouveau-n&eacute;s d√©pist√©s avec sexe ratio  
	              </div>
	              
	              <div style="width: 100%; margin-top: 10px; font-family: Goudy Old Style; font-size: 19px; font-weight: normal;"> 
	                  <?php echo ($this->nbPatientDVSM + $this->nbPatientDVSF); ?> d√©pist√©s :
	              </div>
	              
	              <div style="width: 100%; height: 20px; margin-top: 5px; margin-bottom: 15px; font-family: Goudy Old Style; background: re;" align="center">
	             
	                <table style="height: 36px; border: 1px solid #cccccc;">
	                  <tr style="height: 18px; border: 1px solid #cccccc;">
	                    <td style=" border: 2px solid #cccccc; padding-left: 6px; padding-right: 6px;"> Masculin </td>
	                    <td style=" border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; text-align: right; min-width: 50px;"> <?php echo $this->nbPatientDVSM; ?> </td>
	                    <?php if( count($this->pourcentageDepistagesValides) == 2){ ?>
    	                  <td style=" border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; text-align: right;"> <?php echo $this->pourcentageDepistagesValides[0]." %"; ?> </td>
	                    <?php } ?>
	                  </tr>
	                  <tr style="width: 100%; height: 18px; border: 1px solid #cccccc;">
	                    <td style=" border: 2px solid #cccccc; padding-left: 6px; padding-right: 6px;"> F√©minin </td>
	                    <td style=" border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; text-align: right; min-width: 50px;"> <?php echo $this->nbPatientDVSF; ?> </td>
	                    <?php if( count($this->pourcentageDepistagesValides) == 2){ ?>
    	                  <td style=" border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; text-align: right;"> <?php echo $this->pourcentageDepistagesValides[1]." %"; ?> </td>
	                    <?php } ?>
	                  </tr>
	                
	                </table>
	             
	              </div>
	              
	              <div style="width: 100%; margin-top: 60px; font-family: Goudy Old Style; font-size: 19px; font-weight: normal;"> 
	                  <span style="font-weight: bold; font-size: 22px;"> sex-ratio = </span>  <?php echo $this->nbPatientDVSM."/".$this->nbPatientDVSF; ?> = <?php echo number_format(($this->nbPatientDVSM / $this->nbPatientDVSF),2,',', ' '); ?>
	              </div>
	              
	            </td>
	            
	            
	            <!-- DEUXIEME COLONNE -->
	            <!-- DEUXIEME COLONNE -->
	            <td style="width: 67%; height: 10px; background: gree; text-align: center; vertical-align: top;">
	              
	              <!-- Les diffÈrents types d'hÈmogobine rencontrÈs -->
   	              <!-- Les diffÈrents types d'hÈmogobine rencontrÈs -->
	              <div style="width: 100%; font-family: Goudy Old Style; font-size: 21px; font-weight: normal;"> 
	                <span style="font-size: 16px; color: green; font-weight: bold;">&#9883;</span> Les diff&eacute;rents types d'h&eacute;mogobine rencontr&eacute;s 
	              </div>
	              
	              <div style="width: 100%; margin-top: 5px; margin-left: 10px; max-width: 720px; overflow: auto; margin-bottom: 15px; font-family: Goudy Old Style; background: re;" align="center">
	                <table style="height: 36px; border: 1px solid #cccccc;">
	                  <tr style="height: 18px; border: 1px solid #cccccc;">
	                    <?php for( $i = 0 ; $i < count($this->differentsTypesProfils[0]) ; $i++){ ?>
    	                  <td style="min-width: 90px; border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; font-weight: bold; text-align: center;"> <?php echo $this->differentsTypesProfils[0][$i]; ?> </td>
	                    <?php } ?>
	                  </tr>
	                  
	                  <tr style="height: 18px; border: 1px solid #cccccc;">
	                    <?php for( $i = 0 ; $i < count($this->differentsTypesProfils[0]) ; $i++){ ?>
    	                  <td style="border: 2px solid #cccccc; padding-left: 10px; text-align: center;"> 
    	                    <span style="font-weight: bold;"><?php echo $this->differentsTypesProfils[1][$this->differentsTypesProfils[0][$i]].' '; ?> </span>
    	                    <?php echo ' - ('.$this->pourcentageDifferentsTypesProfils[$i].'%)'; ?>
    	                  </td>
	                    <?php } ?>
	                  </tr>
	                  
	                </table>
	              </div>
	            
	              <div style="width: 100%; font-family: Goudy Old Style; font-size: 21px; font-weight: normal;">
	                <div id="lesDifferentsTypesHemoglobineRencontresPie" style="height: 225px; width: 50%; float: left; "></div>
	                <div id="lesDifferentsTypesHemoglobineRencontresColumn" style="height: 225px; width: 50%; float: left; "></div>
	              </div>
	              
	            </td>
	            
	            
	          </tr>
	          
	          
	          
	          <tr style="width: 100%;"> 
	          
	            <!-- PREMIERE COLONNE -->
	            <!-- PREMIERE COLONNE -->
	            <td colspan="2" style="width: 100%; height: 250px; background: indig; text-align: center; border-top: 2px solid #cccccc; vertical-align: top; ">
	             
	              <!-- RÈpartition des nouveau-nÈs selon leurs ethnies -->
	              <!-- RÈpartition des nouveau-nÈs selon leurs ethnies -->
	              
	              <div style="width: 100%; font-family: Goudy Old Style; font-size: 21px; font-weight: normal; margin-top: 10px;"> 
	                <span style="font-size: 16px; color: green; font-weight: bold;">&#9883;</span> R&eacute;partition des nouveau-n&eacute;s selon leurs ethnies  
	              </div>
	            
	              <div style="width: 100%;" align="center">
	               <div style="width: 100%; margin-top: 5px; max-width: 1090px; overflow: auto; margin-bottom: 15px; font-family: Goudy Old Style;" >
	                <table style="height: 36px; border: 1px solid #cccccc;">
	                  <tr style="height: 18px; border: 1px solid #cccccc;">
	                    <?php for( $i = 0 ; $i < count($this->peresNouveauNesSelonEthnies[0]) ; $i++){ ?>
    	                  <td style="min-width: 90px; border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; font-weight: bold; text-align: center;"> <?php echo $this->peresNouveauNesSelonEthnies[0][$i]; ?> </td>
	                    <?php } ?>
	                  </tr>
	                  
	                  <tr style="height: 18px; border: 1px solid #cccccc;">
	                    <?php for( $i = 0 ; $i < count($this->peresNouveauNesSelonEthnies[0]) ; $i++){ ?>
    	                  <td style="border: 2px solid #cccccc; padding-left: 10px; text-align: center;"> 
    	                    <span style="font-weight: bold;"><?php echo $this->peresNouveauNesSelonEthnies[1][$this->peresNouveauNesSelonEthnies[0][$i]].' '; ?> </span>
    	                    <?php echo ' - ('.$this->pourcentagePeresNouveauNesSelonEthnies[$i].'%)'; ?>
    	                  </td>
	                    <?php } ?>
	                  </tr>
	                  
	                </table>
	               </div>
	              </div>
	              
	              <div style="width: 100%; font-family: Goudy Old Style; font-size: 21px; font-weight: normal;">
	                <div id="repartitionSelonEthniesPie" style="height: 225px; width: 30%; float: left;"></div>
	                <div style="height: 225px; width: 5%; float: left;"></div>
	                <div id="repartitionSelonEthnies" style="height: 225px; width: 65%; float: left;"></div>
	              </div>
	              
	              
	            </td>
	             
	          </tr>  
	          
	          <tr style="width: 100%;"> 
	          
	            <!-- PREMIERE COLONNE -->
	            <!-- PREMIERE COLONNE -->
	            <td colspan="2" style="width: 100%; height: 250px; background: indig; text-align: center; border-top: 2px solid #cccccc; vertical-align: top; ">
	             
	              <!-- RÈpartition des diffÈrents types d'hÈmoglibine rencontrÈs selon leurs ethnies -->
	              <!-- RÈpartition des diffÈrents types d'hÈmoglibine rencontrÈs selon leurs ethnies -->
	              
	              <div style="width: 100%; font-family: Goudy Old Style; font-size: 21px; font-weight: normal; margin-top: 10px;"> 
	                <span style="font-size: 16px; color: green; font-weight: bold;">&#9883;</span> R&eacute;partition des diff&eacute;rents types d'h&eacute;moglobine selon l'ethnie
	              </div>
	            
	              <div style="width: 100%;" align="left">
	              
	               <div style="width: 5.1%; margin-top: 5px; margin-bottom: 15px; font-family: Goudy Old Style; float: left; background: re;" >
	                 <table style="height: 36px; border: 1px solid #cccccc;">
	                   <tr style="height: 18px; border: 1px solid #cccccc;">
	                     <td style="width: 100%; border: 2px solid #cccccc; padding-left: 5px; padding-right: 5px; text-align: center;"> St </td>
	                   </tr>
	                   <?php for( $i = 0 ; $i < count($this->repartitionTypesProfilsSelonEthnies[0]) ; $i++){ ?>
	                     <tr style="height: 18px; border: 1px solid #cccccc;">
    	                   <td style="min-width: 15px; border: 2px solid #cccccc; text-align: center; font-weight: bold;"> 
    	                     <?php echo $this->repartitionTypesProfilsSelonEthnies[0][$i]; ?>
    	                   </td>
	                     </tr>
	                 <?php } ?>
	                 </table>
	               </div>
	               
	               
	               
	               <div style="width: 94.9%; margin-top: 5px; max-width: 1090px; overflow: auto; margin-bottom: 15px; font-family: Goudy Old Style; float: left;" >
	                <table style="height: 36px; border: 1px solid #cccccc;">
	                  <tr style="height: 18px; border: 1px solid #cccccc;">
	                    <?php for( $i = 0 ; $i < count($this->repartitionTypesProfilsSelonEthnies[1]) ; $i++ ){ ?>
    	                  <td style="min-width: 90px; border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; font-weight: bold; text-align: center;"> <?php echo $this->repartitionTypesProfilsSelonEthnies[1][$i]; ?> </td>
	                    <?php } ?>
	                  </tr>
	                  
	                  <?php  
	                     for($i = 0 ; $i < count($this->repartitionTypesProfilsSelonEthnies[0]) ; $i++){
                             $profil = $this->repartitionTypesProfilsSelonEthnies[0][$i];
                      ?>
                      <tr style="height: 18px; border: 1px solid #cccccc;">
                      <?php 
	                       for($j = 0 ; $j < count($this->repartitionTypesProfilsSelonEthnies[1]) ; $j++){ 
	                           $ethnie = $this->repartitionTypesProfilsSelonEthnies[1][$j];
	                           $tousLesProfils = $this->repartitionTypesProfilsSelonEthnies[2][$ethnie];
	                           $nbParProfils =  array_count_values($tousLesProfils);
	                  ?>
	                           
    	                         <td style="min-width: 15px; border: 2px solid #cccccc; padding-left: 10px; text-align: center; font-weight: bold;"> 
    	                           <?php 
    	                           if (in_array($profil, $tousLesProfils)){
                                         echo $nbParProfils[$profil];
                                   }else{
                                         echo '-';
                                   }
                                   ?>
    	                         </td>
	                           
	                  <?php } ?> 
                           </tr>
                      <?php } ?>
	                  
	                </table>
	               </div>
	               
	              </div>
	              
	              <!--div style="width: 100%; font-family: Goudy Old Style; font-size: 21px; font-weight: normal;">
	                <div id="repartitionDesDifferentsProfilsSelonEthniesPie" style="height: 225px; width: 30%; float: left;"></div>
	                <div style="height: 225px; width: 5%; float: left;"></div>
	                <div id="repartitionDesDifferentsProfilsSelonEthnies" style="height: 225px; width: 65%; float: left;"></div>
	              </div-->
	              
	              
	            </td>
	             
	          </tr>  
	          
	          
	          
	          <tr style="width: 100%;"> 
	          
	            <!-- PREMIERE COLONNE -->
	            <!-- PREMIERE COLONNE -->
	            <td colspan="2" style="width: 100%; height: 150px; background: indig; text-align: center; border-top: 2px solid #cccccc; vertical-align: top; ">
	             
	              <!-- Les professions rencontrÈes chez les mËres et chez les pËres -->
	              <!-- Les professions rencontrÈes chez les mËres et chez les pËres -->
	              
	              <div style="width: 100%; font-family: Goudy Old Style; font-size: 21px; font-weight: normal; margin-top: 10px;"> 
	                <span style="font-size: 16px; color: green; font-weight: bold;">&#9883;</span> Les professions rencontr&eacute;es chez les m&egrave;res  
	              </div>
	            
	              <div style="width: 100%;" align="center">
	               <div style="width: 100%; margin-top: 5px; max-width: 1090px; overflow: auto; margin-bottom: 15px; font-family: Goudy Old Style;" >
	                <table style="height: 36px; border: 1px solid #cccccc;">
	                  <tr style="height: 18px; border: 1px solid #cccccc;">
	                    <?php for( $i = 0 ; $i < count($this->repartitionProfessionChezLesMeres[0]) ; $i++){ ?>
    	                  <td style="min-width: 90px; border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; font-weight: bold; text-align: center;"> <?php echo $this->repartitionProfessionChezLesMeres[0][$i]; ?> </td>
	                    <?php } ?>
	                  </tr>
	                  
	                  <tr style="height: 18px; border: 1px solid #cccccc;">
	                    <?php for( $i = 0 ; $i < count($this->repartitionProfessionChezLesMeres[0]) ; $i++){ ?>
    	                  <td style="border: 2px solid #cccccc; padding-left: 10px; text-align: center;"> 
    	                    <span style="font-weight: bold;"><?php echo $this->repartitionProfessionChezLesMeres[1][$this->repartitionProfessionChezLesMeres[0][$i]].' '; ?> </span>
    	                    <?php echo ' - ('.$this->pourcentageDifferentsProfessionMeres[$i].'%)'; ?>
    	                  </td>
	                    <?php } ?>
	                  </tr>
	                  
	                </table>
	               </div>
	              </div>
	              
	            </td>
	             
	          </tr>  
	          
	          
	          
	          <tr style="width: 100%;"> 
	          
	            <!-- PREMIERE COLONNE -->
	            <!-- PREMIERE COLONNE -->
	            <td colspan="2" style="width: 100%; height: 150px; background: indig; text-align: center;  vertical-align: top; ">
	             
	              <!-- Les professions rencontrÈes chez les mËres et chez les pËres -->
	              <!-- Les professions rencontrÈes chez les mËres et chez les pËres -->
	              
	              <div style="width: 100%; font-family: Goudy Old Style; font-size: 21px; font-weight: normal; margin-top: 10px;"> 
	                <span style="font-size: 16px; color: green; font-weight: bold;">&#9883;</span> Les professions rencontr&eacute;es chez les p&egrave;res  
	              </div>
	            
	              <div style="width: 100%;" align="center">
	               <div style="width: 100%; margin-top: 5px; max-width: 1090px; overflow: auto; margin-bottom: 15px; font-family: Goudy Old Style;" >
	                <table style="height: 36px; border: 1px solid #cccccc;">
	                  <tr style="height: 18px; border: 1px solid #cccccc;">
	                    <?php for( $i = 0 ; $i < count($this->repartitionProfessionChezLesPeres[0]) ; $i++){ ?>
    	                  <td style="min-width: 90px; border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; font-weight: bold; text-align: center;"> <?php echo $this->repartitionProfessionChezLesPeres[0][$i]; ?> </td>
	                    <?php } ?>
	                  </tr>
	                  
	                  <tr style="height: 18px; border: 1px solid #cccccc;">
	                    <?php for( $i = 0 ; $i < count($this->repartitionProfessionChezLesPeres[0]) ; $i++){ ?>
    	                  <td style="border: 2px solid #cccccc; padding-left: 10px; text-align: center;"> 
    	                    <span style="font-weight: bold;"><?php echo $this->repartitionProfessionChezLesPeres[1][$this->repartitionProfessionChezLesPeres[0][$i]].' '; ?> </span>
    	                    <?php echo ' - ('.$this->pourcentageDifferentsProfessionPeres[$i].'%)'; ?>
    	                  </td>
	                    <?php } ?>
	                  </tr>
	                  
	                </table>
	               </div>
	              </div>
	              
	            </td>
	             
	          </tr>
	          
	          
	          <tr style="width: 100%;"> 
	          
	            <!-- PREMIERE COLONNE -->
	            <!-- PREMIERE COLONNE -->
	            <td colspan="2" style="width: 100%; height: 150px; background: indig; text-align: center;  vertical-align: top; ">
	             
	              <!-- La rÈpartition des nouveaux nÈs par adresses -->
	              <!-- La rÈpartition des nouveaux nÈs par adresses -->
	              
	              <div style="width: 100%; font-family: Goudy Old Style; font-size: 21px; font-weight: normal; margin-top: 10px;"> 
	                <span style="font-size: 16px; color: green; font-weight: bold;">&#9883;</span> La r&eacute;partition des nouveau-n&eacute;s par adresse 
	              </div>
	            
	              <div style="width: 100%;" align="center">
	               <div style="width: 100%; margin-top: 5px; max-width: 1090px; overflow: auto; margin-bottom: 15px; font-family: Goudy Old Style;" >
	                <table style="height: 36px; border: 1px solid #cccccc;">
	                  <tr style="height: 18px; border: 1px solid #cccccc;">
	                    <?php for( $i = 0 ; $i < count($this->repartitionPatientDepistesParAdresses[0]) ; $i++){ ?>
    	                  <td style="min-width: 90px; border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; font-weight: bold; text-align: center;"> <?php echo $this->repartitionPatientDepistesParAdresses[0][$i]; ?> </td>
	                    <?php } ?>
	                  </tr>
	                  
	                  <tr style="height: 18px; border: 1px solid #cccccc;">
	                    <?php for( $i = 0 ; $i < count($this->repartitionPatientDepistesParAdresses[0]) ; $i++){ ?>
    	                  <td style="border: 2px solid #cccccc; padding-left: 10px; text-align: center;"> 
    	                    <span style="font-weight: bold;"><?php echo $this->repartitionPatientDepistesParAdresses[1][$this->repartitionPatientDepistesParAdresses[0][$i]].' '; ?> </span>
    	                    <?php echo ' - ('.$this->pourcentagePatientDepistesParAdresses[$i].'%)'; ?>
    	                  </td>
	                    <?php } ?>
	                  </tr>
	                  
	                </table>
	               </div>
	              </div>
	              
	            </td>
	             
	          </tr>
	          
	          
	          <tr style="width: 100%;"> 
	          
	            <!-- PREMIERE COLONNE -->
	            <!-- PREMIERE COLONNE -->
	            <td colspan="2" style="width: 100%; height: 150px; background: indig; text-align: center;  vertical-align: top; ">
	             
	              <!-- RÈpartition des nouveaux nÈs dÈpistÈs de j=0 au j=8 -->
	              <!-- RÈpartition des nouveaux nÈs dÈpistÈs de j=0 au j=8 -->
	              
	              <div style="width: 100%; font-family: Goudy Old Style; font-size: 21px; font-weight: normal; margin-top: 10px;"> 
	                <span style="font-size: 16px; color: green; font-weight: bold;">&#9883;</span> R&eacute;partition des nouveaux n&eacute;s d&eacute;pist&eacute;s du j=0 au j=N  
	              </div>
	            
	              <div style="width: 100%;" align="center">
	               <div style="width: 100%; margin-top: 5px; max-width: 1090px; overflow: auto; margin-bottom: 15px; font-family: Goudy Old Style;" >
	                <table style="height: 36px; border: 1px solid #cccccc;">
	                  <tr style="height: 18px; border: 1px solid #cccccc;">
	                    <?php for( $i = 0 ; $i < count($this->effectifPatientDepistesAges[3]) ; $i++){ ?>
    	                  <td style="min-width: 90px; border: 2px solid #cccccc; padding-left: 10px; padding-right: 5px; font-weight: bold; text-align: center;"> j<?php echo $this->effectifPatientDepistesAges[3][$i]; ?> </td>
	                    <?php } ?>
	                  </tr>
	                  
	                  <tr style="height: 18px; border: 1px solid #cccccc;">
	                    <?php for( $i = 0 ; $i < count($this->effectifPatientDepistesAges[3]) ; $i++){ ?>
    	                  <td style="border: 2px solid #cccccc; padding-left: 10px; text-align: center;"> 
    	                    <span style="font-weight: bold;"><?php echo $this->effectifPatientDepistesAges[2][$this->effectifPatientDepistesAges[3][$i]].' '; ?> </span>
    	                    <?php echo ' - ('.$this->pourcentageEffectifPatientDepistesAges[$i].'%)'; ?>
    	                  </td>
	                    <?php } ?>
	                  </tr>
	                  
	                </table>
	               </div>
	              </div>
	              
	            </td>
	             
	          </tr>  
	          
	          
	          
	          
	          
	          
	          
	        </table>
	       
	      </div> 
	    </td>
	  </tr>	 
	          
	          
	</table>

</div>

<!-- LA TROISIEME PAGE POUR INFOS 3 -->
<!-- LA TROISIEME PAGE POUR INFOS 3 -->
<!-- LA TROISIEME PAGE POUR INFOS 3 -->
<div id="contenuPageC" >
    <table style="width: 100%; height: 20%;">
	 <tr style="background: white; width: 100%; vertical-align: top;"><td colspan="3"> <img id="retourPageCMenuInfos" style="width: 16px;position: absolute; height: 16px; float: left; cursor: pointer; " src='../images_icons/72.png' > <!--a style='float: right; position: absolute; right: 50px; text-decoration: none;' href="javascript:captureImage();" title=""> &#9775; </a--> </td></tr>

	 </table>

</div>

<!-- LA QUATRIEME PAGE POUR INFOS 4 -->
<!-- LA QUATRIEME PAGE POUR INFOS 4 -->
<!-- LA QUATRIEME PAGE POUR INFOS 4 -->
<div id="contenuPageD" >
    <table style="width: 100%; height: 20%;">
	  <tr style="background: white; width: 100%; vertical-align: top;"><td colspan="3"> <img id="retourPageDMenuInfos" style="width: 16px;position: absolute; height: 16px; float: left; cursor: pointer; " src='../images_icons/72.png' > </td></tr>
	 
	  <tr style="width: 100%; vertical-align: top; background: yello; ">
	    <td align="center" style="width: 100%;">
	      <div style="width: 100%; background: re;">
	        
	        <table style="width: 100%;">
	          <tr style="width: 100%;">
	          
	            <!-- PremiËre colonne -->
	            <td align="right" style="width: 50%; height: 100px; background: re; vertical-align: top;" >
    	            <?php echo $this->headScript()->appendFile($this->basePath().'/js/consultation/jsCarteInteractive.js');?>
     		        <div style="width: 97%; text-align: center; font-family: time new roman;">Carte des zones ayant des depist&eacute;s dans la r&eacute;gion de Saint-Louis</div>
     		        <div id='chartSaintlouis'></div>
                    <div id='chartSaintlouisScript'> </div>
    	            <script type="text/javascript">carteZonesSaintLouis();</script>
	            </td>
	            
	            <!-- DeuxiËme colonne -->
	            <td align="center" style="width: 50%; height: 100px; background: yello; border-left: 2px solid #cccccc; vertical-align: top; " >
    	            <div style="width: 97%; text-align: center; font-family: time new roman;" id="colZoneSelect">Carte de la zone <span>s&eacute;lectionn&eacute;e</span></div>
    	            <div id='chartSenegal' style='margin-top: 30px;'></div>
    	            <div id='chartSenegalScript'></div> 
    	            <script type="text/javascript"></script>
	            </td>
	          
	          </tr>
	        </table>
	        
	      </div>
	    </td>
	  </tr>
	 
	</table>
	
	
	
	
	

</div>











<!-- MENU GENERAL  -- MENU GENERAL -->
<!-- MENU GENERAL  -- MENU GENERAL -->
<!-- MENU GENERAL  -- MENU GENERAL -->
<div id="menuGeneral">

  <table style="width: 100%;">
    <tr style="width: 100%; height: 50px;" >
      <td style="width: 25%;">
      
            <div id="menuOption1" style='width: 90%; margin: auto;'>
		      <table style="width: 100%; border-radius: 50%;">
		          <tr style="border-radius: 50%; height: 120px;">
		             <th style="border-radius: 50%; ">
		               <div>
		                 <section>
		                   <img style="width: 40px; height: 40px; margin-top: -15px;" src='../images_icons/bar-un-diagramme-48.png' /> G&Eacute;N&Eacute;RAL 
		                 </section>
		               </div>
		             </th>
		          </tr>
		       </table>
		    </div>
		    
      </td>
      
      <td style="width: 25%;" > 
      
            <div id="menuOption2" style='width: 90%; margin: auto;'>
		      <table style="width: 100%; border-radius: 50%;">
		          <tr style="border-radius: 50%; height: 120px;">
		             <th style="border-radius: 50%; ">
		               <div>
		                 <section>
   		                   <img style="width: 40px; height: 40px; margin-top: -15px;" src='../images_icons/autres infos.png' /> AUTRES INFOS
		                 </section>
		               </div>
		             </th>
		          </tr>
		       </table>
		    </div>
		    
      </td>
      
      <td style="width: 25%;" >
      
            <div id="menuOption3" style='width: 90%; margin: auto;'>
		      <table style="width: 100%; border-radius: 50%;">
		          <tr style="border-radius: 50%; height: 120px;">
		             <th style="border-radius: 50%; ">
		               <div>
		                 <section>
		                   <img style="width: 40px; height: 40px; margin-top: -15px;" src='../images_icons/param 2.png' /> PARAM&Eacute;TRABLE
		                 </section>
		               </div>
		             </th>
		          </tr>
		       </table>
		    </div>
		    
      </td>
      
      <td style="width: 25%;" >
      
            <div id="menuOption4" style='width: 90%; margin: auto;'>
		      <table style="width: 100%; border-radius: 50%;">
		          <tr style="border-radius: 50%; height: 120px;">
		             <th style="border-radius: 50%; ">
		               <div>
		                 <section>
		                   <img src='../images_icons/Table16X16.png' > CARTE INTERACTIVE
		                 </section>
		               </div>
		             </th>
		          </tr>
		       </table>
		    </div>
		    
      </td>
      
    </tr>
  </table>

</div>


</div>


<script>
    setTimeout(function(){ $('#contenuPageA, #contenuPageB, #contenuPageC, #contenuPageD').toggle(false); });
    initialisation();
</script>
