<script>
var base_url = window.location.toString();
var tabUrl = base_url.split("public");
//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_menu_consultations').toggle(true);
$("#menu_consultations").replaceWith("<li id='menu_consultations' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
dep_menu_consultation1();
$('#menu_historique_consultation_style').css({'font-weight':'bold','color':'white','font-size':'22px'});
</script>

<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/consultation/styleListePaientsConsultes.css');?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/dateTimePicker/jquery-ui-timepicker-addon.css');?>


<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/consultation/jsListePatientsConsultes.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/dateTimePicker/jquery-ui-timepicker-addon.js');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/sendMail.js');?>


<?php use Facturation\View\Helper\DateHelper;
$Control = new DateHelper();?>
<style>
#contenuInterface{ visibility: hidden; }
</style>

<script>
$(window).load(function () {

	$('#wait').toggle(false);
	$('#contenuInterface').fadeIn().css({'visibility':'visible'});
	 
});
</script>


<div id="titre" style='font-family: police2; text-decoration:none; color: green; font-size: 18px; font-weight: bold; padding-left: 20px;'><iS style='font-size: 25px;'>&curren;</iS> <span> LISTE DES PATIENTS ADMIS </span></div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>
<div id="contenuInterface" >
<div id="contenu" >

		<table class="table table-bordered tab_list_mini" id="patientAdmis">
			<thead>
				<tr style="height:45px; width:100%;">
				    <th id="numero" align="center">N&deg; dossier</th>
					<th id="nom" align="center">Nom</th>
					<th id="prenom" align="center">Prenom</th>
					<th id="date" align="center" >Date naiss.</th>
					<th id="sexe" align="center" >Sexe</th>
					<th id="adresse" align="center" >Adresse</th>
					<th id="effectuer" align="center">Options</th>
				</tr>
			</thead>

			<tbody id="donnees" class="liste_patient" style="font-family: times new roman; font-size: 19px;">

            <!-- ******* On affiche la liste des patients ****** -->

			</tbody>

			<tfoot id="foot" class="foot_style">
				<tr>
					<th id="numero_" style="width: 15%;"><input type="text" name="search_browser" value=" N&deg; dossier" class="search_init" /></th>
					<th id="nom_" style="width: 13%;"><input type="text" name="search_browser" value=" Nom" class="search_init" /></th>
					<th id="prenom_" style="width: 18%;"><input type="text" name="search_browser" value=" Prenom" class="search_init" /></th>
					<th id="date_" style="width: 12%;"><input type="text" name="search_browser" value=" Date naissance" class="search_init" /></th>
					<th id="sexe_" style="width: 7%;"><input type="text" name="search_browser" value=" Sexe" class="search_init" /></th>
					<th id="adresse_" style="width: 25%;"><input type="text" name="search_browser" value=" Adresse" class="search_init" /></th>
					<th id="effectuer_" style="width: 10%;"><input type="hidden" name="search_browser" value="" class="" /></th>

				</tr>
			</tfoot>
		</table>

</div>

<div id="interfaceListeFactures">

<div id="vue_patient">
  <!-- Ici on place les details des infos sur le patient, sur la liste des analyses demandées et le bilan du prélèvement  -->
</div>

<div>
  <table style="margin-top: 35px; margin-bottom: 25px; width: 100%;  height: 32px;">
    <tr>
      <td style="width: 42%;"> </td>
      <td style="width: 10%;" id="thoughtbot" class='boutonAnnuler'> </td>
      <td style="width: 10%;" id="thoughtbot" class='boutonTerminer'> </td>
	  <td style="width: 38%;"> </td>
    </tr>
  </table>
</div>

</div>

</div>





<!-- POP UP pour Confirmation Suppression -->
<div id="confirmation" title="Confirmation de la suppression" style="display:none;">
  <p style="font-size: 19px;">
     <span style="float:left; margin:0 0px 20px 0; ">
     <img src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />
     Etes-vous s&ucirc;r de vouloir annuler l'admission ?</span>
  </p>
</div>


<div style='display: none;' class='infos_parentales_tampon'> <!-- à ne pas supprimer *** pour les infos parentales --> </div>


<!-- div id="context-menu">
    <ul class="dropdown-menu" >
         <li><a style="cursor: pointer;" ><img id="visualiserCTX" style='margin-right: 10px; width: 19px; height: 16px;' src='../images_icons/voir2.png'>Visualiser</a></li>
         <li class="divider"></li>
         <li><a id="quitterCTX"  style="cursor: pointer;">Quitter</a></li>
    </ul>
</div-->



<form id="FormulaireImprimerFacture" style="display: none;">
    <button id="ImprimerFacture"></button>
    <input id="idfacturation" type="hidden" value="<?php echo $this->idfacturation; ?>">
</form>


<script type="text/javascript">
$(function(){
	initialisation();
});
$("#interfaceListeFactures").toggle(false);

/*
Email.send ("alhassimdiallobe@gmail.com",
		 "alhassimdiallobe@gmail.com",
		 "Salutation 26-09-18",
		 "Salut  hassim diallo 26-09-18",
		 "smtp.elasticemail.com",
		 "alhassimdiallobe@gmail.com",
		 "7f0b69ce-f08b-4323-a116-0f1ac31b51b9",
		 function done(message){ alert("envoyé") }
); 
*/
		 
</script>

