<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SIMENS '. $this->translate('Systeme Information Medical'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Scripts -->
        <?php 
        
            echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));
        ?>
    </head>
    
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
    </body>
</html>



<script>
/**
 * SCRIPT POUR LANCER LES REQUETES -- SIMENS-BLOC 
 */

function scriptAutoEnvoieAnalysesNonValidees(){

    $.ajax({
        type: 'POST',
        url: tabUrl[0]+'public/consultation/auto-appel-main-fonction' ,
        data:{},
        success: function(data) {

            var result = jQuery.parseJSON(data);  
            // alert(result);
        }
    });

	setTimeout(function(){
		scriptAutoEnvoieAnalysesNonValidees();
	},5000);
}
scriptAutoEnvoieAnalysesNonValidees();
</script>