<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/secretariat/styleDemandesAnalyses.css');?>

<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/secretariat/jsDemandesAnalyses.js');?>

<script type="text/javascript">
var base_url = window.location.toString();
var tabUrl = base_url.split("public");

$('#plus_analyses').toggle(true);
$("#analyses").replaceWith("<li id='analyses' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Analyses </span></a></li>");
dep_analyses1();
$('#analyses_style').css({'font-weight':'bold','color':'white','font-size':'21px'});


$(window).load(function () {
	$('#wait').toggle(false);
	$('#toutLeContenu').fadeIn().css({'visibility':'visible'});
});
</script>

<style>
 #toutLeContenu{ visibility: hidden; };
</style>


<div id="titre" style='font-family: police2; text-decoration:none; color: green; font-size: 18px; font-weight: bold; padding-left: 35px;'><iS style='font-size: 25px;'>&curren;</iS> <span>RECHERCHER LE PATIENT</span></div>
     
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>

<div id="toutLeContenu" >
<div id="contenu" >
        <div style="margin-right: 45px; float:right; font-size: 15px; color: gray; margin-top:5px;"><a style="text-decoration: none; cursor:pointer;" href="javascript:ajouterPatient()" ><img src='../images_icons/aj.gif' /><i style="font-family: Times New Roman; font-size: 15px; color: green;"> Cr&eacute;er un dossier</i></a></div>
		<table style='width:95%; margin-left: 10px; align:center' class="table table-bordered tab_list_mini" id="patient">
			<thead >
			    <tr >
				    <th id="idpatient_" style='width: 15%;'><input type="text" name="search_browser" value=" Num&eacute;ro dossier" class="search_init" /></th>
					<th id="nom_" style='width: 15%;'><input type="text" name="search_browser" value=" Nom" class="search_init" /></th>
					<th id="prenom_" style='width: 17%;'><input type="text" name="search_browser" value=" Pr&eacute;nom" class="search_init" /></th>
					<th id="date_" style='width: 13%;'><input type="text" name="search_browser" value=" Date naissance" class="search_init" /></th>
					<th id="adresse_" style='width: 35%;'><input type="text" name="search_browser" value=" Adresse" class="search_init" /></th>
					<th id="effectuer_" style='width: 5%;'><input type="hidden" value="" class="" />Options</th>

				</tr>

			</thead>

			<tbody id="donnees" class="liste_patient" style="font-family: times new roman; font-size: 19px;">

	            <?php /* AFFICHAGE DE LA LISTE DES PATIENTS */?>

			</tbody>

		</table>

</div>

<div id="demandesAnalyses">
   <input type="hidden" id="idpatient">
   <input type="hidden" id="verifModifier">
   
   <div id="vue_patient">   </div>
   
   <div id="listeDemandesAnalyses" align="center" >   
   
   <?php echo  $this->headScript()->appendFile($this->basePath().'/js/secretariat/ajoutDemandesAnalyses.js'); ?>
   
     <div style="width: 94%; margin-bottom: 30px; margin-top: 30px;">
       <div id="accordions" align="left" >  
           <div style='font-family: police2; font-size: 18px; font-weight: bold; background: #efefef;'>Choisir les analyses </div>
           <div id='listeDemandesAnalysesApresChargement' style='max-height: 450px; border-top: 1px solid #cccccc;'>
           
                <div id='montantTotal' style='cursor: pointer; float:right; margin-top: 5px;'> <span style='padding-left: 20px; color: green; font-size: 17px; font-family: times new roman;'> </span> <hass> <a href="javascript:imprimerAnalyse();" ><img style="margin-top: -15px; float: right; cursor: pointer;" src="../images_icons/pdf.png"  title="Imprimer" /></a> </hass> </div>
                
                <div style="border-bottom: 1px solid gray; margin-top: 30px; margin-bottom: 10px;"></div>
                
                 <div id="lesDemandesAnalyses" style="width: 100%; height:400px;">
				                  
				    <table class="table table-bordered" style="width: 100%; margin-bottom: 0px; margin-left: 0px; ">
			             <thead style="width: 100%;">
				            <tr style="width: 100%; height: 40px; font-family: police2;">
				              <th style="width:  4%; font-weight: bold; font-size: 15px; ">N&ordm;</th>
				              <th style="width: 25%; font-weight: bold; font-size: 15px; text-align: left;">Type d'analyse</th>
				              <th style="width: 47%; font-weight: bold; font-size: 15px; text-align: left;">Analyse</th>
				              <th style="width: 15%; font-weight: bold; font-size: 15px; text-align: left;">Tarif (FCFA) </th>
				              <th style="width:  9%; font-weight: bold; font-size: 15px; ">Options</th>
				            </tr>
				          </thead>
			        </table>
			                         
				    <div id="Acte_0">
					 <!-- A ne pas enlever -->
					</div>
					<input type='hidden' id='diagnostic_demande_text' >
					<!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
					<!--********************* BOUTON AJOUTER-SUPPRIMER ************************-->
					<div id="controls_acte" style="margin-top: 20px; width: 100%;">
					     <div style="width: 100%;">
					         <div style="width: 3%; float: left; cursor: pointer; " id="supprimer_acte">
					            <img style='margin-left: 5px;' src='../images_icons/moin-green.png' title='supprimer' />
					         </div>
					         <div style="width: 3%; float: left; cursor: pointer; " id="ajouter_acte">
					            <img style='margin-left: 5px;' src='../images_icons/plus-green.png' title='ajouter' />
					         </div>
					     </div>
				    </div>
				                
                    <!--********************* BOUTON VALIDER OU MODIFIER ************************-->
                    <!--********************* BOUTON VALIDER OU MODIFIER ************************-->
                    <table style="width: 90%; float:right; position: relative; right: 0;">
                         <tr style="width: 100%;">
                             <th style="height:15px;">
                                <div id='bouton_Acte_valider_demande' style="float:right;">
                                     <button >Valider</button>
                                </div>
                                <div id='bouton_Acte_modifier_demande' style="float:right;">
                                     <button >Modifier</button>
                                </div>
                              </th>
                         </tr>
                     </table>
				                
     		      </div>
           
           
                            <!--********************* CHARGEMENT DES DONNEES  ************************-->
                            <!--********************* CHARGEMENT DES DONNEES  ************************-->
                            <!--********************* CHARGEMENT DES DONNEES  ************************-->
                            <script> 
                               ValiderDemandeActe();
                            </script>
           
           
           
           
           </div>
       </div>
     </div>
       
     <table style="margin-top: 35px; margin-bottom: 30px; width: 100%;  height: 12px;">
	   <tr>
	     <td style="width: 42%;"> </td>
	     <td style="width: 10%;" id="thoughtbot" class='boutonAnnuler' > </td>
	     <td style="width: 10%;" id="thoughtbot" class='boutonTerminer'> </td>
	     <td style="width: 38%;"> </td>
	   </tr>
     </table>
       
   </div>

   <form id="FormulaireImprimerDemandesAnalyses" style="display: none;">
       <button id="ImprimerDemandesAnalyses"></button>
    </form>
    
</div>

</div>



<div id="visualisation" title="Informations" style="display:none;">
    <div id="info" style="font-size: 16px;">
    </div>
</div>


<div id="context-menu">
    <ul class="dropdown-menu" >
         <li><a style="cursor: pointer;" ><img id="visualiserCTX" style='margin-right: 10px; width: 19px; height: 16px;' src='../images_icons/voir2.png'>Visualiser</a></li>
         <li class="divider2"></li>
         <li><a style="cursor: pointer;"><img  id="suivantCTX" style='margin-right: 10px; width: 19px; height: 16px;' src='../images_icons/transfert_droite.png'>Suivant</a></li>
         <li class="divider"></li>
         <li><a id="quitterCTX"  style="cursor: pointer;">Quitter</a></li>
    </ul>
</div>
		
		
<div style='display: none;' class='infos_parentales_tampon'> <!-- à ne pas supprimer *** pour les infos parentales --> </div>

		
<script type="text/javascript">
  initialisation(); 
</script>