<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/secretariat/styleListePatient.css');?>

<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/secretariat/jsListepatient.js');?>

<style>
#contenuInterface{ visibility: hidden; };
</style>

<script type="text/javascript">
$(window).load(function () {
	$('#wait').toggle(false);
	$('#contenuInterface').fadeIn().css({'visibility':'visible'});
});
</script>

<div id="titre" style='font-family: police2; text-decoration: none; color: green; font-size: 19px; font-weight: bold; padding-left:20px;'>
	<iS style='font-size: 25px;'>&curren;</iS>
	<span> LISTE DES PATIENTS </span>
</div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>

<div id="contenuInterface" >
<div id="contenu">

            <span style='float: right; margin-right: 30px; margin-top: 5px; font-size: 12px; font-weight: normal; font-family: police2; color: green;'>  <span style='cursor:pointer; font-weight: bold; font-size: 19px;' id='patientTous'> Tous </span> <span style='font-size: 18px;'> | </span> <span style='cursor:pointer;' id='patientsDepistes'> D&eacute;pist&eacute;s </span> <span style='font-size: 18px;'> | </span> <span style='cursor:pointer;' id='patientsExternes'> Externes </span> </span>                                     
            <div id="t_neg_pos" style='float: right; margin-right: 50px; margin-top: 5px; display: none; width: 50px;' > 
               <div id="t_negatif" style="width: 45%; float: left; "> <img style='cursor: pointer; ' src="<?php echo $this->basePath().'/images_icons/t_negatif.png';?>" title="Test n&eacute;gatif" /> </div> 
               <div id="t_positif" style="width: 45%; float: left; "> <img style='cursor: pointer; ' src="<?php echo $this->basePath().'/images_icons/t_positif.png';?>" title="Test positif" /> </div> 
            </div> 
			
			<table class="table table-bordered tab_list_mini" id="patient">
				<thead>
					<tr style="height: 45px; width:100%;">
					    <th id="numero_dossier" style='cursor: pointer;'>N&deg; dossier</th>
						<th id="nom" style='cursor: pointer;'>Nom</th>
						<th id="prenom" style='cursor: pointer;'>Pr&eacute;nom</th>
						<th id="date" style='cursor: pointer;'>Date. naiss</th>
						<th id="sexe" style='cursor: pointer;'>Sexe</th>
						<th id="adresse" style='cursor: pointer;'>Adresse</th>
						<th id="nationalite" style='cursor: pointer;'>Nationalit&eacute;</th>
						<th id="effectuer">Options</th>
					</tr>
				</thead>

				<tbody id="donnees" class="liste_patient" style="font-family: times new roman; font-size: 19px;">

					<!-- ************ On affiche les patients en une liste ordonnï¿½e************ -->

				</tbody>

				<tfoot id="foot" class="foot_style">
					<tr>
					    <th id="numero_dossier_" style='width: 14%;'><input type="text" name="search_browser"
							value=" N&deg; dossier" class="search_init" /></th>
						<th id="nom_" style='width: 13%;'><input type="text" name="search_browser"
							value=" Nom" class="search_init" /></th>
						<th id="prenom_" style='width: 15%;'><input type="text" name="search_browser"
							value=" Pr&eacute;nom" class="search_init" /></th>
						<th id="date_" style='width: 12%;'><input type="text" name="search_browser"
							value=" Date naissance" class="search_init" /></th>
						<th id="sexe_" style='width: 7%;'><input type="text" name="search_browser"
							value=" Sexe" class="search_init" /></th>
						<th id="adresse_" style='width: 19%;'><input type="text" name="search_browser"
							value=" Adresse" class="search_init" /></th>
						<th id="nationalite_" style='width: 10%;'><input type="text" name="search_browser"
							value=" Nationalit&eacute;" class="search_init" /></th>
						<th id="effectuer_" style='width: 10%;'><input type="hidden" name="search_browser"
							value="" class="" /></th>

					</tr>
				</tfoot>
			</table>
</div>


<div id="vue_patient">

</div>

</div>


<!-- POP UP pour Confirmation Suppression -->
<div id="confirmation" title="Confirmation de la suppression"
	style="display: none;">
	<p style="font-size: 16px;">
		<span style="float: left; margin: 0 0px 20px 0;"> <img
			src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />
			Etes-vous s&ucirc;r de vouloir supprimer le patient ?
		</span>

	</p>
</div>

<div id="context-menu">
    <ul class="dropdown-menu" >
         <li><a style="cursor: pointer;" ><img id="visualiserCTX" style='margin-right: 10px; width: 19px; height: 16px;' src='../images_icons/voir2.png'>Visualiser</a></li>
         <li class="divider2"></li>
         <li><a style="cursor: pointer;"><img  id="modifierCTX" style='margin-right: 10px; width: 19px; height: 16px;' src='../images_icons/pencil_16.png'>Modifier</a></li>
         <li class="divider"></li>
         <li><a id="quitterCTX"  style="cursor: pointer;">Quitter</a></li>
    </ul>
</div>

<div style='display: none;' class='infos_parentales_tampon'> <!-- à ne pas supprimer *** pour les infos parentales --> </div>

<script type="text/javascript">

$(function(){
	initialisation();
});

$('#vue_patient').toggle(false);

var base_url = window.location.toString();
var tabUrl = base_url.split("public");
//POUR LE MENU GAUCHE dans -menugauche.phtml
$('#plus_dossier_patient').toggle(true);
$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Dossier patient </span></a></li>");
dep_dossier_patient1();
$('#liste_dossier_patient_style').css({'font-weight':'bold','color':'white','font-size':'22px'});

</script>
