<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/secretariat/styleSecretariat.css');?>

<!-- MES JS -->
<?php
echo $this->headScript ()->appendFile ( $this->basePath () . '/js/secretariat/jsSecretariat.js' );
echo $this->headLink ()->appendStylesheet ( $this->basePath () . '/css/Facturation/DatePicker.css' );
?>

<script>
controle_saisie();

var base_url = window.location.toString();
var tabUrl = base_url.split("public");
//POUR LE MENU GAUCHE dans -elementgauche.phtml


//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_dossier_patient').toggle(true);
$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Dossier Patient </span></a></li>");
dep_dossier_patient1();
$('#liste_dossier_patient_style').css({'font-weight':'bold','color':'white','font-size':'22px'});
</script>


<script type="text/javascript">
$(window).load(function () {
	$('#wait').toggle(false);
	$('#contenu').fadeIn().css({'visibility':'visible'});
});
</script>

<style>
#contenu{ visibility: hidden; };
</style>



<?php
$form = $this->form;
$form->setAttribute ( 'action', $this->url ( 'secretariat', array ('action' => 'modifier-patient') ) );
$form->setAttribute ('enctype','multipart/form-data');
$this->form->prepare ();
echo $this->form ()->openTag ( $form );
?>

<div id="titre" style='font-family: police2; text-decoration:none; color: green; font-size: 18px; font-weight: bold; padding-left: 30px;'><iS style='font-size: 25px;'>&curren;</iS> MODIFIER L'ETAT CIVIL DU PATIENT</div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>
<div id="contenu" >

    <?php echo $this->formRow($form->get('idpersonne'));?>
	
	<div style='width: 100%;'>
    
	 <div style='width: 15%; height: 150px; float:left;'>
		<div class="photo_patient" id='photo'>
            <img id="modifier_photo" src="<?php echo $this->basePath().'/img/photos_patients/'.$this->photo.''?>" style=' margin-left:-10px; margin-top:-10px; width:105px; height:105px;'/>
			<input type='file' name="fichier" />
			<!-- RECUPERER L'IMAGE -->
		</div>
		<input type='hidden' id="fichier_tmp" name="fichier_tmp" />
		
		<div id='form_radio' style='width: 90px; heigth: 20px; margin-top: 170px; margin-left: 10px;' > 
		  <?php echo $this->formRow($this->form->get('typepatient'));?>
		  <?php echo $this->formRow($form->get('depistage'));?>
		</div>
     </div>
     
	 <div style='width: 80%; height: 150px; float:left;'>
		<table style='width: 100%;' id="form_patient" style="float: left;">

			<tr class="comment-form-patient">
                     <td style="width: 33%; "> <?php echo $this->formRow($this->form->get('sexe'));?></td>
                     <td style="width: 33%; "> <?php echo $this->formRow($this->form->get('lieu_naissance'));?></td>
                     <td style="width: 33%; "> <?php echo $this->formRow($this->form->get('email'));?></td>

                  </tr>

                  <tr class="comment-form-patient">
                     <td > <?php echo $this->formRow($this->form->get('nom'));?></td>
                     <td > <?php echo $this->formRow($this->form->get('telephone'));?></td>
                     <td > <?php echo $this->formRow($this->form->get('situation_matrimoniale'));?></td>
                     <td style='display: none;'> <?php echo $this->formRow($this->form->get('ethnie'));?></td>
                  </tr>

                  <tr class="comment-form-patient">
                     <td > <?php echo $this->formRow($this->form->get('prenom'));?></td>
                     <td > <?php echo $this->formRow($this->form->get('profession'));?></td>
                     <td > <?php echo $this->formRow($this->form->get('nationalite_actuelle'));?></td>
                  </tr>

                  <tr class="comment-form-patient">
                     <td style="width: 33%;"> 
                       <div class="age" style="float: left; width: 33%;"> <?php echo $this->formRow($this->form->get('age'));?> </div>
                       <div class="date_naiss" style="float: left; width: 60%;"> <?php echo $this->formRow($this->form->get('date_naissance'));?> </div>
                     </td>
                     <td > <?php echo $this->formRow($this->form->get('adresse'));?></td>
                     <td > <?php echo $this->formRow($this->form->get('nationalite_origine'));?>  </td>
                  </tr>

		</table>
	  </div>
		
	  <div style='width: 3%; height: 150px; float:left;'>
		<div class="barre_vertical"></div>

		<div class="vider_formulaire" id="vider_champ">
			<hass> <input type="submit" title="Vider tout" name="vider"
				id="vider"> </hass>
		</div>

		<div class="supprimer_photo" id="div_supprimer_photo">
			<hass> <input name="supprimer_photo"> </hass>
			<!-- balise sans importance pour le moment -->
		</div>

		<div class="modifer_donnees" id="div_modifier_donnees">
			<hass> <input alt="modifer_donnees" title="modifer les donnees"
				name="modifer_donnees" id="modifer_donnees"> </hass>
		</div>
      </div>
    </div>
	
	<table style="margin-top: 365px; width: 100%;  height: 12px;">
	  
	  <tr style="">
	  <td style="width: 42%;"></td>
	  <td style="width: 10%;" id="thoughtbot" >
		<button id="annuler"
			style="font-family: police2; font-size: 17px; font-weight: bold;">
			Annuler
		</button>
	  </td>
	  
	  <td style="width: 10%;" id="thoughtbot">
		<button type="submit" name="terminer" id="terminer"
			style=" font-family: police2; font-size: 17px; font-weight: bold;">
			Terminer
		</button>
	  </td>
	  
	  <td style="width: 38%;"></td>
	  
	  </tr>
    </table>

</div>

<!-- POP UP pour Confirmation Suppression -->
<div id="confirmation" title="Confirmation de la suppression"
	style="display: none;">
	<p style="font-size: 16px;">
		<span style="float: left; margin: 0 0px 20px 0;"> <img
			src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />

			Etes-vous s&ucirc;r de vouloir supprimer la photo ?
		</span>
	</p>
</div>


<!-- LES BOUTONS "TERMINER" ou "VALIDER" -->

<?php echo $this->form()->closeTag();?>


<script> 
if($('#date_naissance').val()){
    $('#age').attr('readonly', true);
} 

$('#annuler').click(function(){ 
	 vart=tabUrl[0]+'public/secretariat/liste-patient';
     $(location).attr("href",vart);
     return false;
});

//GESTION DES BOUTONS RADIO
//GESTION DES BOUTONS RADIO
//GESTION DES BOUTONS RADIO
var boutonsTypePatient = $('#form_radio input[name="typepatient"]');
$(boutonsTypePatient).click(function(){

	if(boutonsTypePatient[0].checked){
		$('#interne_patient').parent().css({'font-weight' : 'normal',  'font-size' : '13px', 'color' : 'black', 'font-family' : 'times new roman'});
		$('#interne_patient_img').remove();
		
		$('#externe_patient').parent().css({'font-weight' : 'bold',  'font-size' : '15px', 'color' : 'green', 'font-family' : 'Iskoola Pota'});
		$('#externe_patient_img').remove();
		$('#externe_patient').parent().append('<img id="externe_patient_img" style="padding-left: 10px;" src="'+tabUrl[0]+'public/images_icons/tick-icon1.png">');

	}else
		if(boutonsTypePatient[1].checked){
			$('#externe_patient').parent().css({'font-weight' : 'normal',  'font-size' : '13px', 'color' : 'black', 'font-family' : 'times new roman'});
			$('#externe_patient_img').remove();
			
			$('#interne_patient').parent().css({'font-weight' : 'bold',  'font-size' : '15px', 'color' : 'green', 'font-family' : 'Iskoola Pota'});
			$('#interne_patient_img').remove();
			$('#interne_patient').parent().append('<img id="interne_patient_img" style="padding-left: 10px;" src="'+tabUrl[0]+'public/images_icons/tick-icon1.png">');
			
		}
});

</script>
    
    
    
    
<?php if( $this->typepatient == 1 ) {?>
  <script>
    $('#interne_patient').parent().trigger('click'); 
    $('#interne_patient').parent().css({'font-weight' : 'bold',  'font-size' : '15px', 'color' : 'green', 'font-family' : 'Iskoola Pota'});
    $('#interne_patient').parent().append('<img id="externe_patient_img" style="padding-left: 10px;" src="'+tabUrl[0]+'public/images_icons/tick-icon1.png">');
  </script>
<?php }else{ ?>
  <script>
    $('#externe_patient').parent().trigger('click'); 
    $('#externe_patient').parent().css({'font-weight' : 'bold',  'font-size' : '15px', 'color' : 'green', 'font-family' : 'Iskoola Pota'});
    $('#externe_patient').parent().append('<img id="externe_patient_img" style="padding-left: 10px;" src="'+tabUrl[0]+'public/images_icons/tick-icon1.png">');
  </script>
<?php } ?>


<!-- ***** GESTION DES PATIENTS DEPISTES ***** -->
<!-- ***** GESTION DES PATIENTS DEPISTES ***** -->
<!-- ***** GESTION DES PATIENTS DEPISTES ***** -->
<?php if( $this->depistage == false ) { ?>
  <script>
    $('#form_radio').toggle(false);
    $('#situation_matrimoniale').parent().toggle(true);
    $('#ethnie').parent().toggle(false);
    $('#nationalite_origine').parent().toggle(true);
    $('#depistage').val(0);
  </script>
<?php }else if( $this->depistage == true ) { ?>
  <script>
    $('#situation_matrimoniale').parent().toggle(false);
    $('#ethnie').parent().toggle(true);
    $('#nationalite_origine').parent().toggle(false);
    $('#depistage').val(1);
  </script>
<?php } ?>
