# RainbowBox
# Copyright (C) 2015-2016 Jean-Baptiste LAMY
# LIMICS (Laboratoire d'informatique médicale et d'ingénierie des connaissances en santé), UMR_S 1142
# University Paris 13, Sorbonne paris-Cité, Bobigny, France

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Source code generated by the VIIIP platform.

from rainbowbox       import *
from rainbowbox.color import *
from rainbowbox.order_elements import *

color_2 = hsv2rgb(0.13, 0.25, 1.0)
color_1 = hsv2rgb(0.13, 0.55 , 1.0)

color_5_grave = hsv2rgb(0.0, 0.15, 1.0)
color_4_grave = hsv2rgb(0.0, 0.25, 1.0)
color_3_grave = hsv2rgb(0.0, 0.35, 1.0)
color_2_grave = hsv2rgb(0.0, 0.5 , 1.0)
color_1_grave = hsv2rgb(0.0, 0.6 , 1.0)

groupe_0   = PropertyGroup("Hypersensibility")
groupe_5   = PropertyGroup("Infection")
groupe_7   = PropertyGroup("Tumor")
groupe_10  = PropertyGroup("Hematology")
groupe_20  = PropertyGroup("Endocrine, nutritional et metabolic")
groupe_30  = PropertyGroup("Comportemental")
groupe_40  = PropertyGroup("Nervous system")
groupe_50  = PropertyGroup("Eye and ear")
groupe_60  = PropertyGroup("Cardiovascular")
groupe_70  = PropertyGroup("Pulmonar")
groupe_80  = PropertyGroup("Digestive")
groupe_90  = PropertyGroup("Skin")
groupe_100 = PropertyGroup("Osteomuscular")
groupe_110 = PropertyGroup("Urogenital")
groupe_120 = PropertyGroup("Age")
groupe_130 = PropertyGroup("Pregnancy")

element_group_1 = ElementGroup("""Prostaglandin E1""")
element_group_2 = ElementGroup("""Phosphodiesterase type 5 inhibitors""")

element_1 = Element(element_group_1, """Vitaros""", details = """alprostadil""")
element_2 = Element(element_group_1, """Edex""", details = """alprostadil""")
element_3 = Element(element_group_1, """Caverject""", details = """alprostadil""")
element_4 = Element(element_group_1, """Muse""", details = """alprostadil""")
element_5 = Element(element_group_2, """Viagra""", details = """sildenafil""")
element_6 = Element(element_group_2, """Cialis""", details = """tadalafil""")
element_7 = Element(element_group_2, """Levitra""", details = """vardenafil""")
element_8 = Element(element_group_2, """Spedra""", details = """avanafil""")
elements = [element_1, element_2, element_3, element_4, element_5, element_6, element_7, element_8]

property_ci_1 = Property(groupe_0, """Hyper&shy;sensibility to prostaglandins""", order_key = (-9223372036854775807, "Hyper&shy;sensibilité prostaglandines"))
property_ci_2 = Property(groupe_40, """<img width="40" src="vcm_past--patho-vessel--brain.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>History of cerebrovascular events<div style="clear: both;"></div>""", order_key = (1926512, "Antécédents d'accident cérébro&shy;vasculaire"))
property_ci_4 = Property(groupe_40, """<img width="40" src="vcm_current--hypo--cerebral_function.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Syncope<div style="clear: both;"></div>""", order_key = (2414944, "Syncope"))
property_ci_5 = Property(groupe_50, """<img width="40" src="vcm_current--genetic--eye.svg" style="float: right; margin-top: -0.1em;"/>Retinitis pigmentosa<div style="clear: both;"></div>""", order_key = (2667168, "Rétinite pigmentaire"))
property_ci_6 = Property(groupe_60, """<img width="40" src="vcm_current--hypo-vessel_bp.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Hypo&shy;tension<div style="clear: both;"></div>""", order_key = (3024224, "Hypo&shy;tension"))
property_ci_7 = Property(groupe_60, """<img width="40" src="vcm_current--hypo-vessel_bp.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Orthostatic Hypo&shy;tension<div style="clear: both;"></div>""", order_key = (3024224, "Hypo&shy;tension orthostatique"))
property_ci_8 = Property(groupe_60, """<img width="40" src="vcm_current--hyper-vessel_bp.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Arterial hyper&shy;tension<div style="clear: both;"></div>""", order_key = (3037664, "Hyper&shy;tension artérielle"))
property_ci_10 = Property(groupe_60, """<img width="40" src="vcm_current--patho--heart.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Pathology contraindicating sexual activity<div style="clear: both;"></div>""", order_key = (3284064, "Pathologie contre-indiquant l'activité sexuelle"))
property_ci_11 = Property(groupe_60, """<img width="40" src="vcm_current--patho-vessel--heart.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Anginous pain during sexual intercourses<div style="clear: both;"></div>""", order_key = (3297504, "Douleur angineuse au cours des rapports sexuels"))
property_ci_13 = Property(groupe_60, """<img width="40" src="vcm_past--obstructed_vessel-patho--heart.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>History of myocardial infarction<div style="clear: both;"></div>""", order_key = (3306352, "Antécédents d'infarctus du myocarde"))
property_ci_14 = Property(groupe_60, """<img width="40" src="vcm_past--hypo--heart.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>History of cardiac failure<div style="clear: both;"></div>""", order_key = (3328752, "Antécédents d'insuf&shy;fi&shy;sance cardiaque"))
property_ci_17 = Property(groupe_60, """<img width="40" src="vcm_past--patho--heart_rhythm.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>History of severe heart rhythm disorders<div style="clear: both;"></div>""", order_key = (3360112, "Antécédents de troubles du rythme sévères"))
property_ci_18 = Property(groupe_60, """<img width="40" src="vcm_current--patho--heart_rhythm.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Non-control&shy;led heart rhythm disorders<div style="clear: both;"></div>""", order_key = (3360224, "Troubles du rythme non contrôlés"))
property_ci_19 = Property(groupe_80, """<img width="40" src="vcm_current--hypo--liver.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Severe hepatic failure<div style="clear: both;"></div>""", order_key = (5156704, "Insuf&shy;fi&shy;sance hépatique sévère"))
property_ci_20 = Property(groupe_50, """<img width="40" src="vcm_current--nerve-patho--eye.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Loss of vision in one eye due to anterior ischemic non-arteritic optic neuropathy<div style="clear: both;"></div>""", order_key = (5264224, "Perte de la vision d'un oeil due à une neuropathie optique ischémique antérieure non artéritique"))
property_ci_21 = Property(groupe_110, """<img width="40" src="vcm_current--physio--genital.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Sexual intercourse without a condom with childbearing age or pregnant women<div style="clear: both;"></div>""", order_key = (6325984, "Rapports sexuels sans préservatif avec femme en âge de procréer ou enceinte"))
property_ci_22 = Property(groupe_110, """<img width="40" src="vcm_current--physio--genital_female.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Female<div style="clear: both;"></div>""", order_key = (6402144, "Femme"))
property_ci_23 = Property(groupe_110, """<img width="40" src="vcm_current--patho--genital_male--treatment--implant.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Port of penile implant<div style="clear: both;"></div>""", order_key = (6787488, "Port d'implant pénien"))
property_ci_24 = Property(groupe_110, """<img width="40" src="vcm_current--inflammation--genital_male.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Balanitis<div style="clear: both;"></div>""", order_key = (6814304, "Balanite"))
property_ci_25 = Property(groupe_110, """<img width="40" src="vcm_risk--pain--genital_male.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Predisposition to priapism<div style="clear: both;"></div>""", order_key = (6823376, "Prédisposition au priapisme"))
property_ci_26 = Property(groupe_110, """<img width="40" src="vcm_current--hypo--kidney.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Severe renal failure<div style="clear: both;"></div>""", order_key = (6984544, "Insuf&shy;fi&shy;sance rénale sévère"))
property_ci_27 = Property(groupe_110, """<img width="40" src="vcm_current--arrest--kidney.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>End-stage renal failure requiring dialysis<div style="clear: both;"></div>""", order_key = (6993504, "Insuf&shy;fi&shy;sance rénale terminale nécessitant une dialyse"))
property_ci_28 = Property(groupe_110, """<img width="40" src="vcm_current--inflammation--urinary_bladder.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Male uretritis<div style="clear: both;"></div>""", order_key = (7423584, "Urétrite masculine"))
property_ci_29 = Property(groupe_110, """<img width="40" src="vcm_current--malformation--genital_male.svg" style="float: right; margin-top: -0.1em; margin-left: -7px;"/>Anatomic malformation of penis<div style="clear: both;"></div>""", order_key = (14394464, "Malformation anatomique du pénis"))
property_ci_age       = Property(groupe_120, """<img width="40" src="vcm_current--physio--age_class.svg" style="float: right; margin-top: -0.1em;"/>Age<div style="clear: both;"></div>""", order_key = (0, "Âge"), start_new_box = True)
property_ci_grossesse = Property(groupe_130, """<img width="40" src="vcm_current--physio--pregnancy.svg" style="float: right; margin-top: -0.1em;"/>Pregnancy<div style="clear: both;"></div>""", order_key = (0, "Grossesse"))

relations_ci = [
  Relation(element_1, property_ci_1, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_2, property_ci_1, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_3, property_ci_1, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_4, property_ci_1, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_5, property_ci_2, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_6, property_ci_2, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_7, property_ci_2, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_1, property_ci_4, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_5, property_ci_5, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_7, property_ci_5, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_8, property_ci_5, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_5, property_ci_6, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_6, property_ci_6, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_7, property_ci_6, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_8, property_ci_6, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_1, property_ci_7, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_8, property_ci_8, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_6, property_ci_8, hatch = 0, details = """<span class='rouge'>contre-indiqué</span> (non-controlled)""", widget="""<div class="severite">(non-controlled)</div>"""),
  Relation(element_1, property_ci_10, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_2, property_ci_10, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_3, property_ci_10, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_4, property_ci_10, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_5, property_ci_10, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_6, property_ci_10, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_7, property_ci_10, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_8, property_ci_10, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_6, property_ci_11, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_8, property_ci_11, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_5, property_ci_13, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_6, property_ci_13, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_7, property_ci_13, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_8, property_ci_13, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_6, property_ci_14, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_8, property_ci_17, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_6, property_ci_18, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_5, property_ci_19, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_7, property_ci_19, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_8, property_ci_19, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_5, property_ci_20, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_6, property_ci_20, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_7, property_ci_20, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_8, property_ci_20, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_1, property_ci_21, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_2, property_ci_21, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_3, property_ci_21, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_4, property_ci_21, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_1, property_ci_22, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_2, property_ci_22, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_3, property_ci_22, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_4, property_ci_22, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_5, property_ci_22, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_6, property_ci_22, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_7, property_ci_22, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_8, property_ci_22, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_2, property_ci_23, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_3, property_ci_23, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_1, property_ci_24, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_4, property_ci_24, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_1, property_ci_25, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_2, property_ci_25, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_3, property_ci_25, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_4, property_ci_25, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_6, property_ci_26, hatch = 1, details = """<span class='orange'>déconseillé</span>"""),
  Relation(element_8, property_ci_26, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_7, property_ci_27, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_1, property_ci_28, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_4, property_ci_28, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_1, property_ci_29, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_2, property_ci_29, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_3, property_ci_29, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_4, property_ci_29, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_1, property_ci_age, widget = """<div class="popupspan"><center><table cellspacing="1" class="barre_de_couleur" style="width: 80%;margin-bottom: 0px; margin-top: 0.4em;" ><tr><td width="19%" class="barre_de_couleur_ci"><div class="barre_nombre" style="margin-left: -0em;">&nbsp;</div></td><td width="81%" class="barre_de_couleur_ok"><div class="barre_nombre" style="margin-left: -0.76em;">18</div></td></tr></table></center><span style='text-align: left;'>Child below 18 : contraindicated</span></div>
"""),
  Relation(element_2, property_ci_age, widget = """<div class="popupspan"><center><table cellspacing="1" class="barre_de_couleur" style="width: 80%;margin-bottom: 0px; margin-top: 0.4em;" ><tr><td width="16%" class="barre_de_couleur_ci"><div class="barre_nombre" style="margin-left: -0em;">&nbsp;</div></td><td width="84%" class="barre_de_couleur_ok"><div class="barre_nombre" style="margin-left: -0.76em;">15</div></td></tr></table></center><span style='text-align: left;'>Child : contraindicated</span></div>
"""),
  Relation(element_3, property_ci_age, widget = """<div class="popupspan"><center><table cellspacing="1" class="barre_de_couleur" style="width: 80%;margin-bottom: 0px; margin-top: 0.4em;" ><tr><td width="16%" class="barre_de_couleur_ci"><div class="barre_nombre" style="margin-left: -0em;">&nbsp;</div></td><td width="84%" class="barre_de_couleur_ok"><div class="barre_nombre" style="margin-left: -0.76em;">15</div></td></tr></table></center><span style='text-align: left;'>Child below 15 : contraindicated</span></div>
"""),
  Relation(element_4, property_ci_age, widget = """<div class="popupspan"><center><table cellspacing="1" class="barre_de_couleur" style="width: 80%;margin-bottom: 0px; margin-top: 0.4em;" ><tr><td width="16%" class="barre_de_couleur_ci"><div class="barre_nombre" style="margin-left: -0em;">&nbsp;</div></td><td width="84%" class="barre_de_couleur_ok"><div class="barre_nombre" style="margin-left: -0.76em;">15</div></td></tr></table></center><span style='text-align: left;'>Child : contraindicated</span></div>
"""),
  Relation(element_5, property_ci_age, widget = """<div class="popupspan"><center><table cellspacing="1" class="barre_de_couleur" style="width: 80%;margin-bottom: 0px; margin-top: 0.4em;" ><tr><td width="19%" class="barre_de_couleur_ci"><div class="barre_nombre" style="margin-left: -0em;">&nbsp;</div></td><td width="81%" class="barre_de_couleur_ok"><div class="barre_nombre" style="margin-left: -0.76em;">18</div></td></tr></table></center><span style='text-align: left;'>Child below 18 : contraindicated</span></div>
"""),
  Relation(element_6, property_ci_age, widget = """<div class="popupspan"><center><table cellspacing="1" class="barre_de_couleur" style="width: 80%;margin-bottom: 0px; margin-top: 0.4em;" ><tr><td width="19%" class="barre_de_couleur_ci"><div class="barre_nombre" style="margin-left: -0em;">&nbsp;</div></td><td width="81%" class="barre_de_couleur_ok"><div class="barre_nombre" style="margin-left: -0.76em;">18</div></td></tr></table></center><span style='text-align: left;'>Child below 18 : contraindicated</span></div>
"""),
  Relation(element_7, property_ci_age, widget = """<div class="popupspan"><center><table cellspacing="1" class="barre_de_couleur" style="width: 80%;margin-bottom: 0px; margin-top: 0.4em;" ><tr><td width="19%" class="barre_de_couleur_ci"><div class="barre_nombre" style="margin-left: -0em;">&nbsp;</div></td><td width="81%" class="barre_de_couleur_ok"><div class="barre_nombre" style="margin-left: -0.76em;">18</div></td></tr></table></center><span style='text-align: left;'>Child below 18 : contraindicated</span></div>
"""),
  Relation(element_8, property_ci_age, widget = """<div class="popupspan"><center><table cellspacing="1" class="barre_de_couleur" style="width: 80%;margin-bottom: 0px; margin-top: 0.4em;" ><tr><td width="19%" class="barre_de_couleur_ci"><div class="barre_nombre" style="margin-left: -0em;">&nbsp;</div></td><td width="81%" class="barre_de_couleur_ok"><div class="barre_nombre" style="margin-left: -0.76em;">18</div></td></tr></table></center><span style='text-align: left;'>Child below 18 : contraindicated</span></div>
"""),
]

property_iam_1 = Property(None, """Clarithromycin""", order_key = "Clarithromycine")
property_iam_2 = Property(None, """Doxazosin""", order_key = "Dapoxetine")
property_iam_3 = Property(None, """Nitro and related derivatives""", order_key = "Dérives nitrés et apparentés")
property_iam_4 = Property(None, """Ritonavir-boosted protease inhibitors""", order_key = "Inhibiteurs de protéases boostes par ritonavir")
property_iam_5 = Property(None, """Itraconazole""", order_key = "Itraconazole")
property_iam_6 = Property(None, """Grapefruit juice""", order_key = "Jus de pamplemousse")
property_iam_7 = Property(None, """Ketoconazole""", order_key = "Kétoconazole")
property_iam_8 = Property(None, """Ombitasvir + paritaprevir""", order_key = "Ombitasvir + paritaprevir")
property_iam_9 = Property(None, """Riociguat""", order_key = "Riociguat")
property_iam_10 = Property(None, """Telaprevir""", order_key = "Telaprevir")
property_iam_11 = Property(None, """Telithromycin""", order_key = "Telithromycine")

relations_iam = [
  Relation(element_8, property_iam_1, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_5, property_iam_2, hatch = 1, details = """<span class='orange'>déconseillé</span>"""),
  Relation(element_6, property_iam_2, hatch = 1, details = """<span class='orange'>déconseillé</span>"""),
  Relation(element_7, property_iam_2, hatch = 1, details = """<span class='orange'>déconseillé</span>"""),
  Relation(element_8, property_iam_2, hatch = 1, details = """<span class='orange'>déconseillé</span>"""),
  Relation(element_5, property_iam_3, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_6, property_iam_3, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_7, property_iam_3, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_8, property_iam_3, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_5, property_iam_4, hatch = 1, details = """<span class='orange'>déconseillé</span>"""),
  Relation(element_6, property_iam_4, hatch = 1, details = """<span class='orange'>déconseillé</span>"""),
  Relation(element_7, property_iam_4, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_8, property_iam_4, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_7, property_iam_5, hatch = 1, details = """<span class='orange'>déconseillé</span>"""),
  Relation(element_8, property_iam_5, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_7, property_iam_6, hatch = 1, details = """<span class='orange'>déconseillé</span>"""),
  Relation(element_8, property_iam_6, hatch = 1, details = """<span class='orange'>déconseillé</span>"""),
  Relation(element_7, property_iam_7, hatch = 1, details = """<span class='orange'>déconseillé</span>"""),
  Relation(element_8, property_iam_7, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_5, property_iam_8, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_5, property_iam_9, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_6, property_iam_9, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_7, property_iam_9, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_8, property_iam_9, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_5, property_iam_10, hatch = 1, details = """<span class='orange'>déconseillé</span>"""),
  Relation(element_7, property_iam_10, hatch = 1, details = """<span class='orange'>déconseillé</span>"""),
  Relation(element_8, property_iam_10, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
  Relation(element_8, property_iam_11, hatch = 0, details = """<span class='rouge'>contre-indiqué</span>"""),
]

property_group_ei_SOC_10021881 = PropertyGroup("""Infections and infestations""", order_key = 1)
property_group_ei_SOC_10029104 = PropertyGroup("""Neoplasms benign, malignant and unspecified (incl cysts and polyps)""", order_key = 2)
property_group_ei_SOC_10005329 = PropertyGroup("""Blood and lymphatic system disorders""", order_key = 3)
property_group_ei_SOC_10021428 = PropertyGroup("""Immune system disorders""", order_key = 4)
property_group_ei_SOC_10014698 = PropertyGroup("""Endocrine disorders""", order_key = 5)
property_group_ei_SOC_10027433 = PropertyGroup("""Metabolism and nutrition disorders""", order_key = 6)
property_group_ei_SOC_10037175 = PropertyGroup("""Psychiatric disorders""", order_key = 7)
property_group_ei_SOC_10029205 = PropertyGroup("""Nervous system disorders""", order_key = 8)
property_group_ei_SOC_10015919 = PropertyGroup("""Eye disorders""", order_key = 9)
property_group_ei_SOC_10013993 = PropertyGroup("""Ear and labyrinth disorders""", order_key = 10)
property_group_ei_SOC_10007541 = PropertyGroup("""Cardiac disorders""", order_key = 11)
property_group_ei_SOC_10047065 = PropertyGroup("""Vascular disorders""", order_key = 12)
property_group_ei_SOC_10038738 = PropertyGroup("""Respiratory, thoracic and mediastinal disorders""", order_key = 13)
property_group_ei_SOC_10017947 = PropertyGroup("""Gastrointestinal disorders""", order_key = 14)
property_group_ei_SOC_10019805 = PropertyGroup("""Hepatobiliary disorders""", order_key = 15)
property_group_ei_SOC_10040785 = PropertyGroup("""Skin and subcutaneous tissue disorders""", order_key = 16)
property_group_ei_SOC_10028395 = PropertyGroup("""Musculoskeletal and connective tissue disorders""", order_key = 17)
property_group_ei_SOC_10038359 = PropertyGroup("""Renal and urinary disorders""", order_key = 18)
property_group_ei_SOC_10036585 = PropertyGroup("""Pregnancy, puerperium and perinatal conditions""", order_key = 19)
property_group_ei_SOC_10038604 = PropertyGroup("""Reproductive system and breast disorders""", order_key = 20)
property_group_ei_SOC_10010331 = PropertyGroup("""Congenital, familial and genetic disorders""", order_key = 21)
property_group_ei_SOC_10018065 = PropertyGroup("""General disorders and administration site conditions""", order_key = 22)
property_group_ei_SOC_10022891 = PropertyGroup("""Investigations""", order_key = 23)
property_group_ei_SOC_10022117 = PropertyGroup("""Injury, poisoning and procedural complications""", order_key = 24)
property_group_ei_SOC_10042613 = PropertyGroup("""Surgical and medical procedures""", order_key = 25)
property_group_ei_SOC_10041244 = PropertyGroup("""Social circumstances""", order_key = 26)
property_ei_1 = Property(property_group_ei_SOC_10021428, """Drug hyper&shy;sensitivity""", order_key = "Drug hypersensitivity", details = """<span class="eigrave">Effet grave</span>""")
property_ei_2 = Property(property_group_ei_SOC_10021428, """Angioedema""", order_key = "Angioedema", details = """<span class="eigrave">Effet grave</span>""")
property_ei_3 = Property(property_group_ei_SOC_10029205, """Ischaemic stroke""", order_key = "Ischaemic stroke", details = """<span class="eigrave">Effet grave</span>""")
property_ei_4 = Property(property_group_ei_SOC_10029205, """Haemorrhagic stroke""", order_key = "Haemorrhagic stroke", details = """<span class="eigrave">Effet grave</span>""")
property_ei_5 = Property(property_group_ei_SOC_10029205, """Transient ischaemic attack""", order_key = "Transient ischaemic attack", details = """<span class="eigrave">Effet grave</span>""")
property_ei_6 = Property(property_group_ei_SOC_10029205, """Dizziness""", order_key = "Dizziness", details = """""")
property_ei_7 = Property(property_group_ei_SOC_10029205, """Headache""", order_key = "Headache", details = """""")
property_ei_8 = Property(property_group_ei_SOC_10029205, """Seizure""", order_key = "Seizure", details = """<span class="eigrave">Effet grave</span>""")
property_ei_9 = Property(property_group_ei_SOC_10015919, """Nonarteritic anterior ischemic optic neuropathy""", order_key = "Nonarteritic anterior ischemic optic neuropathy", details = """<span class="eigrave">Effet grave</span>""")
property_ei_10 = Property(property_group_ei_SOC_10015919, """Retinal vascular occlusion""", order_key = "Retinal vascular occlusion", details = """<span class="eigrave">Effet grave</span>""")
property_ei_11 = Property(property_group_ei_SOC_10015919, """Chromatopsia""", order_key = "Chromatopsia", details = """""")
property_ei_12 = Property(property_group_ei_SOC_10015919, """Visual disturbance""", order_key = "Visual disturbance", details = """""")
property_ei_13 = Property(property_group_ei_SOC_10015919, """Vision blurred""", order_key = "Vision blurred", details = """""")
property_ei_14 = Property(property_group_ei_SOC_10007541, """Supraventricular extrasystoles""", order_key = "Supraventricular extrasystoles", details = """<span class="eigrave">Effet grave</span>""")
property_ei_15 = Property(property_group_ei_SOC_10007541, """Atrial fibrillation""", order_key = "Atrial fibrillation", details = """<span class="eigrave">Effet grave</span>""")
property_ei_16 = Property(property_group_ei_SOC_10007541, """Ventricular arrhythmia""", order_key = "Ventricular arrhythmia", details = """<span class="eigrave">Effet grave</span>""")
property_ei_17 = Property(property_group_ei_SOC_10007541, """Angina pectoris""", order_key = "Angina pectoris", details = """<span class="eigrave">Effet grave</span>""")
property_ei_18 = Property(property_group_ei_SOC_10007541, """Myocardial infarction""", order_key = "Myocardial infarction", details = """<span class="eigrave">Effet grave</span>""")
property_ei_19 = Property(property_group_ei_SOC_10007541, """Sudden cardiac death""", order_key = "Sudden cardiac death", details = """<span class="eigrave">Effet grave</span>""")
property_ei_20 = Property(property_group_ei_SOC_10047065, """Hypo&shy;tension symptomatic""", order_key = "Hypotension symptomatic", details = """""")
property_ei_21 = Property(property_group_ei_SOC_10047065, """Hot flush""", order_key = "Hot flush", details = """""")
property_ei_22 = Property(property_group_ei_SOC_10038738, """Nasal congestion""", order_key = "Nasal congestion", details = """""")
property_ei_23 = Property(property_group_ei_SOC_10017947, """Gastro&shy;oesophageal reflux disease""", order_key = "Gastrooesophageal reflux disease", details = """""")
property_ei_24 = Property(property_group_ei_SOC_10017947, """Dyspepsia""", order_key = "Dyspepsia", details = """""")
property_ei_25 = Property(property_group_ei_SOC_10017947, """Nausea""", order_key = "Nausea", details = """""")
property_ei_26 = Property(property_group_ei_SOC_10040785, """Dermatitis exfoliative""", order_key = "Dermatitis exfoliative", details = """<span class="eigrave">Effet grave</span>""")
property_ei_27 = Property(property_group_ei_SOC_10040785, """Lyell's syndrome""", order_key = "Lyell's syndrome", details = """<span class="eigrave">Effet grave</span>""")
property_ei_28 = Property(property_group_ei_SOC_10040785, """Stevens-Johnson syndrome""", order_key = "Stevens-Johnson syndrome", details = """<span class="eigrave">Effet grave</span>""")
property_ei_29 = Property(property_group_ei_SOC_10040785, """Rash""", order_key = "Rash", details = """""")
property_ei_30 = Property(property_group_ei_SOC_10028395, """Myalgia""", order_key = "Myalgia", details = """""")
property_ei_31 = Property(property_group_ei_SOC_10028395, """Muscle spasms""", order_key = "Muscle spasms", details = """""")
property_ei_32 = Property(property_group_ei_SOC_10028395, """Dorsal pain""", order_key = "Dorsal pain", details = """""")
property_ei_33 = Property(property_group_ei_SOC_10028395, """Pain in extremity""", order_key = "Pain in extremity", details = """""")
property_ei_34 = Property(property_group_ei_SOC_10038359, """Urethral pain""", order_key = "Urethral pain", details = """""")
property_ei_35 = Property(property_group_ei_SOC_10038359, """Urethral bleeding""", order_key = "Urethral bleeding", details = """""")
property_ei_36 = Property(property_group_ei_SOC_10038604, """Penile pain""", order_key = "Penile pain", details = """""")
property_ei_37 = Property(property_group_ei_SOC_10038604, """Penile erythema""", order_key = "Penile erythema", details = """""")
property_ei_38 = Property(property_group_ei_SOC_10038604, """Fibrosis of the corpora cavernosa""", order_key = "Fibrosis of the corpora cavernosa", details = """""")
property_ei_39 = Property(property_group_ei_SOC_10038604, """Peyronie's disease""", order_key = "Peyronie's disease", details = """""")
property_ei_40 = Property(property_group_ei_SOC_10038604, """Penile oedema""", order_key = "Penile oedema", details = """""")
property_ei_41 = Property(property_group_ei_SOC_10038604, """Penile burning sensation""", order_key = "Penile burning sensation", details = """""")
property_ei_42 = Property(property_group_ei_SOC_10038604, """Penis disorder""", order_key = "Penis disorder", details = """""")
property_ei_43 = Property(property_group_ei_SOC_10038604, """Priapism""", order_key = "Priapism", details = """<span class="eigrave">Effet grave</span>""")
property_ei_44 = Property(property_group_ei_SOC_10038604, """Testicular pain""", order_key = "Testicular pain", details = """""")
property_ei_45 = Property(property_group_ei_SOC_10038604, """Vaginal itching""", order_key = "Vaginal itching", details = """""")
property_ei_46 = Property(property_group_ei_SOC_10038604, """Genital pruritus male""", order_key = "Genital pruritus male", details = """""")
property_ei_47 = Property(property_group_ei_SOC_10038604, """Non-specific vaginitis""", order_key = "Non-specific vaginitis", details = """""")
property_ei_48 = Property(property_group_ei_SOC_10038604, """Balanitis""", order_key = "Balanitis", details = """""")
property_ei_49 = Property(property_group_ei_SOC_10038604, """Genital pain male""", order_key = "Genital pain male", details = """""")
property_ei_50 = Property(property_group_ei_SOC_10038604, """Genital erythema""", order_key = "Genital erythema", details = """""")
property_ei_51 = Property(property_group_ei_SOC_10038604, """Genital discomfort""", order_key = "Genital discomfort", details = """""")
property_ei_52 = Property(property_group_ei_SOC_10038604, """Erection prolonged""", order_key = "Erection prolonged", details = """<span class="eigrave">Effet grave</span>""")
property_ei_53 = Property(property_group_ei_SOC_10038604, """Vulvovaginal burning sensation""", order_key = "Vulvovaginal burning sensation", details = """""")
property_ei_54 = Property(property_group_ei_SOC_10018065, """Injection site bruising""", order_key = "Injection site bruising", details = """""")
property_ei_55 = Property(property_group_ei_SOC_10018065, """Chest pain""", order_key = "Chest pain", details = """<span class="eigrave">Effet grave</span>""")
property_ei_56 = Property(property_group_ei_SOC_10018065, """Injection site haematoma""", order_key = "Injection site haematoma", details = """""")


relations_ei = [
  Relation(element_5, property_ei_1, hatch = 0, color = color_3_grave, details = """<span class='moins_frequent'>peu fréquent</span>"""),
  Relation(element_6, property_ei_1, hatch = 0, color = color_3_grave, details = """<span class='moins_frequent'>peu fréquent</span>"""),
  Relation(element_7, property_ei_1, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_5, property_ei_2, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_6, property_ei_2, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_7, property_ei_2, hatch = 0, color = color_3_grave, details = """<span class='moins_frequent'>peu fréquent</span>"""),
  Relation(element_5, property_ei_3, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_6, property_ei_3, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_5, property_ei_4, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_6, property_ei_4, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_5, property_ei_5, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_6, property_ei_5, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_4, property_ei_6, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_5, property_ei_6, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_7, property_ei_6, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_4, property_ei_7, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_5, property_ei_7, hatch = 0, color = color_1, details = """<span class='tres_frequent'>très fréquent</span>"""),
  Relation(element_6, property_ei_7, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_7, property_ei_7, hatch = 0, color = color_1, details = """<span class='tres_frequent'>très fréquent</span>"""),
  Relation(element_8, property_ei_7, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_5, property_ei_8, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_6, property_ei_8, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_7, property_ei_8, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_5, property_ei_9, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_6, property_ei_9, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_7, property_ei_9, hatch = 0, color = color_5_grave, details = """fréquence inconnue"""),
  Relation(element_5, property_ei_10, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_6, property_ei_10, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_5, property_ei_11, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_5, property_ei_12, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_5, property_ei_13, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_2, property_ei_14, hatch = 0, color = color_3_grave, details = """<span class='moins_frequent'>peu fréquent</span>"""),
  Relation(element_3, property_ei_14, hatch = 0, color = color_3_grave, details = """<span class='moins_frequent'>peu fréquent</span>"""),
  Relation(element_5, property_ei_15, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_5, property_ei_16, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_6, property_ei_16, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_7, property_ei_16, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_5, property_ei_17, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_6, property_ei_17, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_7, property_ei_17, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_8, property_ei_17, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_5, property_ei_18, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_6, property_ei_18, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_7, property_ei_18, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_5, property_ei_19, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_6, property_ei_19, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_4, property_ei_20, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_5, property_ei_21, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_6, property_ei_21, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_7, property_ei_21, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_8, property_ei_21, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_5, property_ei_22, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_6, property_ei_22, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_7, property_ei_22, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_8, property_ei_22, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_6, property_ei_23, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_5, property_ei_24, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_6, property_ei_24, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_7, property_ei_24, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_5, property_ei_25, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_6, property_ei_26, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_5, property_ei_27, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_5, property_ei_28, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_6, property_ei_28, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_1, property_ei_29, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_6, property_ei_30, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_3, property_ei_31, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_6, property_ei_32, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_6, property_ei_33, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_1, property_ei_34, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_4, property_ei_34, hatch = 0, color = color_1, details = """<span class='tres_frequent'>très fréquent</span>"""),
  Relation(element_4, property_ei_35, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_1, property_ei_36, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_2, property_ei_36, hatch = 0, color = color_1, details = """<span class='tres_frequent'>très fréquent</span>"""),
  Relation(element_3, property_ei_36, hatch = 0, color = color_1, details = """<span class='tres_frequent'>très fréquent</span>"""),
  Relation(element_4, property_ei_36, hatch = 0, color = color_1, details = """<span class='tres_frequent'>très fréquent</span>"""),
  Relation(element_1, property_ei_37, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_2, property_ei_38, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_2, property_ei_39, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_3, property_ei_39, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_1, property_ei_40, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_1, property_ei_41, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_3, property_ei_41, hatch = 0, color = color_1, details = """<span class='tres_frequent'>très fréquent</span>"""),
  Relation(element_1, property_ei_42, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_1, property_ei_43, hatch = 0, color = color_3_grave, details = """<span class='moins_frequent'>peu fréquent</span>"""),
  Relation(element_2, property_ei_43, hatch = 0, color = color_3_grave, details = """<span class='moins_frequent'>peu fréquent</span>"""),
  Relation(element_3, property_ei_43, hatch = 0, color = color_3_grave, details = """<span class='moins_frequent'>peu fréquent</span>"""),
  Relation(element_4, property_ei_43, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_5, property_ei_43, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_6, property_ei_43, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_7, property_ei_43, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_4, property_ei_44, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_4, property_ei_45, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_1, property_ei_46, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_1, property_ei_47, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_1, property_ei_48, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_1, property_ei_49, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_1, property_ei_50, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_1, property_ei_51, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_1, property_ei_52, hatch = 0, color = color_2_grave, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_2, property_ei_52, hatch = 0, color = color_2_grave, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_3, property_ei_52, hatch = 0, color = color_2_grave, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_4, property_ei_52, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_5, property_ei_52, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_6, property_ei_52, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_7, property_ei_52, hatch = 0, color = color_3_grave, details = """<span class='moins_frequent'>peu fréquent</span>"""),
  Relation(element_1, property_ei_53, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_4, property_ei_53, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_2, property_ei_54, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_3, property_ei_54, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_5, property_ei_55, hatch = 0, color = color_3_grave, details = """<span class='moins_frequent'>peu fréquent</span>"""),
  Relation(element_6, property_ei_55, hatch = 0, color = color_3_grave, details = """<span class='moins_frequent'>peu fréquent</span>"""),
  Relation(element_7, property_ei_55, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_8, property_ei_55, hatch = 0, color = color_4_grave, details = """<span class='moins_frequent'>rare</span>"""),
  Relation(element_2, property_ei_56, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
  Relation(element_3, property_ei_56, hatch = 0, color = color_2, details = """<span class='frequent'>fréquent</span>"""),
]


html_page  = HTMLPage()

order = best_elements_order_np(relations_ci + relations_iam, elements, filter_order = lambda order: order[0] is element_1)
html_ci  = html_page.rainbowbox(relations_ci , elements = elements, order = order, empty_text = "(aucune contre-indication)")
html_iam = html_page.rainbowbox(relations_iam, elements = elements, order = order, empty_text = "(aucune interaction)"     , keep_previous_colors = True)

order = best_elements_order_np(relations_ei, elements, filter_order = lambda order: order[0] is element_1)
html_ei  = html_page.rainbowbox(relations_ei , elements = elements, order = order, empty_text = "(aucun effet indésirable)", keep_previous_colors = True, sort_relation_by_color = True)

html_page.show()
