<html>
<?php echo $this->doctype("XHTML1_TRANSITIONAL"), PHP_EOL; ?>

<meta name="viewport" charset="UTF-8" content="width=device-width, initial-scale=1.0" />
        <?php echo $this->headTitle('SIMENS '. $this->translate('Systeme Information Medical'))->setSeparator(' - ')->setAutoEscape(false) ?>


<?php

 echo $this->headLink()->prependStylesheet($this->basePath().'/css/bootstrap.min.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/uniform.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/select2.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/jquery.contextMenu.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/matrix-style.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/matrix-media.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/font-awesome/css/font-awesome.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/tooltipster.css');
 echo $this->headLink()->appendStylesheet($this->basePath().'/css/smoothness/jquery-ui.css');

  $this->headScript()->appendFile($this->basePath().'/js/jquery.min.js');
  $this->headScript()->appendFile($this->basePath().'/js/jquery.tooltipster.min.js');
  $this->headScript()->appendFile($this->basePath().'/js/bootstrap.min.js');
  $this->headScript()->appendFile($this->basePath().'/js/jquery.uniform.js');
  $this->headScript()->appendFile($this->basePath().'/js/select2.min.js');
  $this->headScript()->appendFile($this->basePath().'/js/jquery.dataTables.min.js');
  $this->headScript()->appendFile($this->basePath().'/js/jquery-ui.js');
  
  $this->headScript()->appendFile($this->basePath().'/js/jquery.maskedinput.js');
  $this->headScript()->appendFile($this->basePath().'/js/controle_saisie/controle_saisie.js');

 echo $this->headTitle($this->pageTitle);?>
		<?php echo $this->headScript();?>
<head>
</head>

<?php
//RECUPERER LES INFOS SUR LE MEDECIN

$user = $this->layout()->user;
$nom = $user['Nom'];
$prenom = $user['Prenom'];
$service = $this->layout()->service;
if($user['role'] == 'superAdmin') { $service = "INFORMATIQUE";}

$sexe = $user['Sexe'];
$civilite =  'Mme';
if($sexe == 'Masculin'){$civilite = 'M';}
?>

<body id = "bodbod">
<!--Header-part-->
<div id="logoSimens" style=" height: 70px;">
			<div style="font-size: 28px; color: red; padding-top: 20px; padding-left: 35px;">+<div style="font-size: 27px; color: #48ce77; font-family: Bookman Old Style; float:left; ">SIMENS</div></div>
	</div>
	
	<!--close-Header-part-->
	<!--top Menu au dessus -->
<div id="user-nav" class="navbar navbar-inverse" style="padding-top: 0px; padding-left: 0px; width: 83%;">
 <div style="width:100%;">
  <ul class="nav" style="width:100%;">
    <li  class="dropdown" style=" width: 30%;"><a title=""  class="dropdown-toggle">
      <i> <span style="color: white; font-size: 13px;">Service: </span></i>
      <b class="caret" ></b> <span style="font-size: 15px; color: white; font-family: Times  New Roman;"><?php echo $service;?></span></a>
    </li>

    <li  class="dropdown" style=" width: 55%;"><a title="" class="dropdown-toggle">
      
      <i><img id="modifierPassword" style="cursor:pointer; position:relative; top:-2px;" src="<?php echo $this->basePath().'/img/light/admin_user_2.png';?>"/>
      </i><span style="color: white; font-size: 13px;"><i>Bienvenue: </i> <?php echo $civilite;?>.</span>
      <b class="caret" ></b> <span style="font-size: 15px; color: white;font-family: Times  New Roman;"><?php echo $prenom.'  '.$nom;?></span></a>
    </li>

    <li style="width: 15%;"><a title="" style="" href="<?php echo $this->url('admin', array('action'=>'logout'));?>">
      <i><img src="<?php echo $this->basePath().'/img/light/bended_arrow_right.png';?>"/> <span style="color: white; font-size: 12px;">D&eacute;connexion</span></i></a>
    </li>
  </ul>
 </div>
</div>

<!--Menu de droite-->
<div id="sidebar">
  <?php echo $this->partial('layout/menugauche'); ?>
</div>
<div id="content">
  	<div id="content-header">
    <div style="width: 96%; margin-left:25px; ">
    	<hr>
   		 <div class="row-fluid">
	         <?php echo $this->content; ?>
         </div>
  	</div>
	</div>
</div>
<!--Pied de Page debut-->
<div class="row-fluid">
	 <div id="footer" class="span12" style="color: white;"><?php echo $this->partial('layout/piedpage'); ?> </div>
</div>
<!--Fin de pied de page-->
</body>
</html>

<style>
.my-custom-theme {

    border-top-left-radius: 5px;
    border-top-right-radius: 5px;
    border-bottom-right-radius: 5px;
    border-bottom-left-radius: 5px;
    background-color: #ffffff;
    background-image: none;
    background-repeat: repeat;
    background-attachment: scroll;
    background-position: 0% 0%;
    background-clip: border-box;
    background-origin: padding-box;
    background-size: auto auto;
    box-shadow: 0px 0px 14px rgba(0, 0, 0, 0.9);
    color: #2c2c2c;
    font-family: 'Arial',sans-serif;
    font-size: 14px;
    line-height: 16px;
    padding-top: 5px;
    /*padding-right: 8px;*/
    padding-bottom: 5px;
    /*padding-left: 10px; */
    font-weight: 400;
    text-align: center;
    weight: bold;
}

.my-custom-theme .tooltipster-content {
    font-family: Arial, sans-serif;
    font-size: 17px;
    line-height: 16px;
    padding: 8px 10px;
}

td {
	font-family: Times  New Roman;
	font-size : 17px;
}
</style>


<script>
var base_url = window.location.toString();
var tabUrl = base_url.split("public");

$(document).ready(function() {
	   $('img').tooltipster({
		   animation: 'grow',
		   delay: 100,
		   theme: '.my-custom-theme',
		   touchDevices: false,
		   trigger: 'hover',
		   position: 'bottom'
		});


	   $('#modifierPassword').click(function(){
	        var role = "<?php echo $user['role'];?>";
	        var id = 0;
	        if(role == 'facturation'){id = 3;}
	        if(role == 'etat_civil' ){id = 9;}
	        
	    	vart=tabUrl[0]+'public/admin/modifier-password/'+id;
	        $(location).attr("href",vart);
	    });

});
</script>