<style>
#sideBareMenuGaucheinfirmerie{ visibility: hidden }
#sideBareMenuGaucheinfirmerie{ min-width:200px; max-width: 430px;}
</style>

<script>
$(window).load(function () {

	$('#waitMenuGaucheinfirmerie').toggle(false);
	$('#sideBareMenuGaucheinfirmerie').fadeIn().css({'visibility':'visible'});
	 
});
</script>

<div id="waitMenuGaucheinfirmerie" style="color: #cccccc; font-size: 13px;  margin-top: 80px;  margin-left: 60px;" > <span> Chargement ... </span> </div>


<ul id="sideBareMenuGaucheinfirmerie">
	<!-- MENU *** infirmerie *** dossier_patient-->
	<li id="menu_infirmerie"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' /> Pr&eacute;l&egrave;vements </span></a> 
	</li>

	<li id="plus_menu_infirmerie" style="background: #4a5765;" >

	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/infirmerie/liste-patient";?>"  >
	       <span id="admission_style_infirm" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;">
	       <img  src='<?php echo $this->basePath().'/images_icons/dossier.png'?>' /> Liste des admis </span></a>
	   </div>

	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/infirmerie/liste-bilan";?>" >
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.png'?>' />
	       <span id="liste_bilan_style_infirm" style="font-size:15px; color: white; font-family:Times New Roman;">Liste des bilans</span></a>
	   </div>
	   
	   <div id="listeAnalysesNonConformes" style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/infirmerie/liste-non-conforme";?>" >
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/warning_16.png'?>' />
	       <span id="liste_bilan_nonconforme_style_infirm" style="font-size:15px; color: white; font-family:Times New Roman;">Non conformit&eacute;</span></a>
	   </div>
	   
	</li>

	
	<!-- MENU *** HISTORIQUE BILAN*** infirmerie -->
	<?php /*?>
	<li id="menu_historique"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Historiques bilans</span></a> 
	</li>

	<li id="plus_menu_historique" style="background: #4a5765;" >

	   <div id="historiquelisteDesBilans" style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/infirmerie/historique-liste-bilans";?>" >
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.png'?>' />
	       <span id="historique_liste_bilan_style" style="font-size:15px; color: white; font-family:Times New Roman;">Liste des bilans</span></a>
	   </div>
	   
	</li>
	<?php */?>
	
	
	<!-- MENU *** CONSULTATIONS*** infirmerie -->
	<li id="menu_consultations"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Consultations</span></a> 
	</li>

	<li id="plus_menu_consultations" style="background: #4a5765;" >

	   <div id="menuDesConsultations" style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/infirmerie/liste-consultations";?>" >
	       <img style="margin-left:5px; margin-top: -7px; display: inline; width: 18px; height: 20px;" src='<?php echo $this->basePath().'/images_icons/list2.png'?>' />
	       <span id="menu_consultations_style" style="font-size:15px; color: white; font-family:Times New Roman;">Liste </span></a>
	   </div>
	   
	   <div id="menuDesConsultations" style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/infirmerie/liste-patients-consultes";?>" >
	       <img style="margin-left:5px; margin-top: -7px; display: inline; width: 18px; height: 20px;" src='<?php echo $this->basePath().'/images_icons/list2.png'?>' />
	       <span id="menu_historique_consultation_style" style="font-size:15px; color: white; font-family:Times New Roman;"> Historique </span></a>
	   </div>
	   
	</li>
	
	
	<!-- MENU *** AFFICHAGE - TABLEAU STATISTIQUE *** infirmerie -->
	<li>
	   <div style="margin-left: 15px; border: 0.5px dashed gray; width: 80%; margin-top: 25px;"> </div>
	   <img onclick="affichageInfosDepistageMensuel();" style="margin-left: 15px; margin-top: 5px; margin-bottom: 5px; display: inline; cursor: pointer;" src='<?php echo $this->basePath().'/img/light/information.png'?>' />
	</li>
	
</ul>


<?php
//CHOISIR LE MENU A AFFICHER SELON QUE C'EST LE MEDECIN OU LE SURVEILLANT
$user = $this->layout()->user;
$role = $user['role'];

$nonConformite = $this->layout()->nonConformite;

if(!$nonConformite){ ?>
<script> $('#listeAnalysesNonConformes').toggle(false); </script>
<?php }

if($role == 'infirmerie'){ ?>
<script> </script>
<?php } ?>


<script>
//*******************************************************************************************************************************
//*******************************************************************************************************************************
//PRELEVEMENT -- PRELEVEMENT
function dep_menu_infirmerie1(){
	$('#menu_infirmerie').click(function(){
		$("#menu_infirmerie").replaceWith("<li id='menu_infirmerie'><a style='cursor: pointer;'><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Pr&eacute;l&egrave;vements </span></a></li>");
		dep_menu_infirmerie2();
	    $('#plus_menu_infirmerie').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_menu_infirmerie2(){
	$('#menu_infirmerie').click(function(){
		$("#menu_infirmerie").replaceWith("<li id='menu_infirmerie' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Pr&eacute;l&egrave;vements </span></a></li>");
		dep_menu_infirmerie1();
	    $('#plus_menu_infirmerie').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_menu_infirmerie').toggle(false);
$('#menu_infirmerie').click(function(){
	$("#menu_infirmerie").replaceWith("<li id='menu_infirmerie' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Pr&eacute;l&egrave;vements </span></a></li>");
	dep_menu_infirmerie1();
$('#plus_menu_infirmerie').animate({
height : 'toggle'
},1000);
return false;
});


//*******************************************************************************************************************************
//*******************************************************************************************************************************
//HISTORIQUE BILAN PRELEVEMENT -- HISTORIQUE BILAN PRELEVEMENT
function dep_menu_historique1(){
	$('#menu_historique').click(function(){
		$("#menu_historique").replaceWith("<li id='menu_historique'><a style='cursor: pointer;'><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman; cursor: pointer;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Historiques bilans </span></a></li>");
		dep_menu_historique2();
	    $('#plus_menu_historique').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_menu_historique2(){
	$('#menu_historique').click(function(){
		$("#menu_historique").replaceWith("<li id='menu_historique' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Historiques bilans </span></a></li>");
		dep_menu_historique1();
	    $('#plus_menu_historique').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_menu_historique').toggle(false);
$('#menu_historique').click(function(){
	$("#menu_historique").replaceWith("<li id='menu_historique' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Historiques bilans </span></a></li>");
	dep_menu_historique1();
$('#plus_menu_historique').animate({
height : 'toggle'
},1000);
return false;
});


//*******************************************************************************************************************************
//*******************************************************************************************************************************
//CONSULTATIONS -- CONSULTATIONS
function dep_menu_consultation1(){
	$('#menu_consultations').click(function(){
		$("#menu_consultations").replaceWith("<li id='menu_consultations'><a style='cursor: pointer;'><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman; cursor: pointer;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Consultations </span></a></li>");
		dep_menu_consultation2();
	    $('#plus_menu_consultations').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_menu_consultation2(){
	$('#menu_consultations').click(function(){
		$("#menu_consultations").replaceWith("<li id='menu_consultations' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
		dep_menu_consultation1();
	    $('#plus_menu_consultations').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_menu_consultations').toggle(false);
$('#menu_consultations').click(function(){
	$("#menu_consultations").replaceWith("<li id='menu_consultations' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
	dep_menu_consultation1();
$('#plus_menu_consultations').animate({
height : 'toggle'
},1000);
return false;
});

</script>


































<?php echo $this->headScript()->appendFile($this->basePath().'/js/infirmerie/jsInfosStatistiquesDepistage.js'); ?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/infirmier/styleInfosStatistiquesDepistage.css');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/jqueryCharts/jquery.canvasjs.min.js');?>

<!--  
*******************************************************************************************************************************
*******************************************************************************************************************************
-->

<!-- GESTION DE L'INTERFACE D'AFFICHAGE DES RESULTATS STATISTIQUES -->
<!-- GESTION DE L'INTERFACE D'AFFICHAGE DES RESULTATS STATISTIQUES -->
<!-- GESTION DE L'INTERFACE D'AFFICHAGE DES RESULTATS STATISTIQUES -->


<div id="affichageInfosStatistiques" title="Afficher des informations statistiques" style="display: none;" >

<div class="optionsPeriode" align="center" style="margin-bottom: 10px;">
    <div class="optionsPeriodePath" align="center" >
       <form id="formOtionsPeriodePath" style="margin-top: -25px;">
          <div class="champOP1">
            <img onclick='imprimerInformationsStatistiques();' src='../images_icons/Apps-Pdf-B-icon-2.png' title='imprimer'>
            <img onclick='afficherInformationsStatistiquesDiagramme();' class='infosDiagramme' src='../images_icons/81.png' style='width: 32px; height: 32px;' title='diagramme'>
            <input type="date" required>
          </div> 
          <div class="champOP2"><input type="date" required><button onclick="getInfosStatistiquesDepistageParPeriode(); return false;">Afficher</button></div>
       </form>
    </div>    
</div>

<div class="zoneResultatsInfosStatiquesDepistage"></div>

<div style='width: 100%;'>
  <div class='affichageInfosTotalDepistage' style='width: 60%; height: 40px; float: right;'>
    <table class='tableauInfosTotalDepistage' style="width: 100%;">
	  <tr style="width: 100%;">
		<td class="infosPath infosPathTotalDepiste" style="width: 50%; height: 40px; text-align: right; padding-right: 15px; font-family: Goudy Old Style; font-size: 21px; font-weight: bold;"><div style="float: left; padding-left: 5px; font-size: 18px;">Total :</div><span></span></td>
		<td class="infosPath " style="width: 50%; height: 40px; text-align: right; padding-right: 15px; font-family: Goudy Old Style; font-size: 12px; font-weight: bold;"></td>
	  </tr>
    </table>
  </div>
</div>


</div>

<div  style="display: none;">
<form id="imprimerInformationsStatistiques"> <button></button> </form>
</div>


<!-- FIN FIN GESTION DE L'INTERFACE D'AFFICHAGE DES RESULTATS STATISTIQUES -->
<!-- FIN FIN GESTION DE L'INTERFACE D'AFFICHAGE DES RESULTATS STATISTIQUES -->
<!-- FIN FIN GESTION DE L'INTERFACE D'AFFICHAGE DES RESULTATS STATISTIQUES -->



<!-- GESTION DE L'INTERFACE D'AFFICHAGE DES DIAGRAMMES RESULTATS STATISTIQUES -->
<!-- GESTION DE L'INTERFACE D'AFFICHAGE DES DIAGRAMMES RESULTATS STATISTIQUES -->
<!-- GESTION DE L'INTERFACE D'AFFICHAGE DES DIAGRAMMES RESULTATS STATISTIQUES -->

<div id="affichageInfosStatistiquesDiagramme" title="Affichage du diagramme des informations" style="display: none;">

<div style="width: 100%; height: 45px; background: re;" align="center">
   <table style='width: 90%;'> 
      <tr style='width: 90%;' id='periodeDiagrammeAfficher'>
        <td style='width: 50%; height: 30px;' id='dateDebutPeriodeDiag'><div style='float: right; height: 25px; background: #f1f1f1; margin-right: 2px;'></div></td> 
        <td style='width: 50%; height: 30px;' id='dateFinPeriodeDiag'>
           <div style='float: left; height: 25px; background: #f1f1f1; margin-left: 2px;'></div>
           <img class='typeDiagrammeColumn iconeDiag' onclick='affichageDiagrammeColumn();' src='../images_icons/bande verticale 24.png' style='width: 24px; height: 24px;' title='bande verticale'>
           <img class='typeDiagrammeBar iconeDiag' onclick='affichageDiagrammeBar();' src='../images_icons/bande horizontale 24.png' style='width: 24px; height: 24px;' title='bande horizontale'>
           <img class='typeDiagrammePie iconeDiag' onclick='affichageDiagrammePie();' src='../images_icons/Actions-office-chart-pie-icon.png' style='width: 24px; height: 24px;' title='circulaire'>
           <img class='typeDiagrammeLine iconeDiag' onclick='affichageDiagrammeLine();' src='../images_icons/Actions-office-chart-line-stacked-icon.png' style='width: 24px; height: 24px;' title='lin&eacute;aire'>
        </td>
      <tr> 
   </table>
</div>

<div style="width: 100%; height: 460px; background: yello;"  align="center" >
   <div id="diagrammeInfosStatistiques">
     <table style="margin-top: 25px; margin-bottom: 15px;"> 
       <tr> 
          <td style="margin-top: 35px; border: 1px solid #ffffff; text-align: center;"> Chargement </td> 
       </tr>  
       <tr> 
          <td align="center" style="border: 1px solid #ffffff; text-align: center;"> 
             <img style="margin-top: 13px; width: 50px; height: 50px;" src="../images/loading/Chargement_1.gif" /> 
          </td> 
       </tr>
     </table>
   </div>
</div>

</div>


<!-- FIN FIN GESTION DE L'INTERFACE D'AFFICHAGE DES DIAGRAMMES RESULTATS STATISTIQUES -->
<!-- FIN FIN GESTION DE L'INTERFACE D'AFFICHAGE DES DIAGRAMMES RESULTATS STATISTIQUES -->
<!-- FIN FIN GESTION DE L'INTERFACE D'AFFICHAGE DES DIAGRAMMES RESULTATS STATISTIQUES -->

<script>
getInfosStatistiquesParDefaut();
</script>