<style>
#sideBareMenuGaucheinfirmerie{ visibility: hidden; }

#sideBareMenuGaucheinfirmerie{ min-width:200px; max-width: 430px;}
</style>

<script>
$(window).load(function () {

	$('#waitMenuGaucheinfirmerie').toggle(false);
	$('#sideBareMenuGaucheinfirmerie').fadeIn().css({'visibility':'visible'});
	 
});
</script>

<div id="waitMenuGaucheinfirmerie" style="color: #cccccc; font-size: 13px;  margin-top: 80px;  margin-left: 60px;" > <span> Chargement ... </span> </div>


<ul id="sideBareMenuGaucheinfirmerie">
	
	<!-- MENU *** CONSULTATIONS*** medecin -->
	
	<?php $user = $this->layout()->user; ?>
    <?php if($user['role'] == 'medecin'){ ?>
	<li id="menu_consultations"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Consultations</span></a> 
	</li>

    
	<li id="plus_menu_consultations" style="background: #4a5765; " >

	   <div id="menuDesConsultations" style="margin-left:30px; height:35px; padding-top:10px; background: yello; border-bottom: solid gray 1px;"><a href="<?php echo $this->basePath()."/consultation/liste-consultations";?>" >
	       <img style="margin-left:5px; margin-top: -7px; display: inline; width: 18px; height: 20px;" src='<?php echo $this->basePath().'/images_icons/list2.png'?>' />
	       <span id="menu_consultations_style" style="font-size:15px; color: white; font-family:Times New Roman;"> En cours </span></a>
	   </div>
	   
	   <div id="menuDesConsultations" style="margin-left:30px; height:35px; padding-top:10px; background: gra;"><a href="<?php echo $this->basePath()."/consultation/liste-patients-consultes";?>" >
	       <img style="margin-left:5px; margin-top: -7px; display: inline; width: 18px; height: 20px;" src='<?php echo $this->basePath().'/images_icons/list2.png'?>' />
	       <span id="menu_historique_consultation_style" style="font-size:15px; color: white; font-family:Times New Roman;"> Historique </span></a>
	   </div>
	   
	</li>
	<?php } ?>
	
	
	<!-- MENU *** STATISTIQUES*** medecin -->
	<li id="menu_statistiques"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' /> Statistiques</span></a> 
	</li>
	
	<li id="plus_menu_statistiques" style="background: #4a5765;" >

	   <div id="menuDesStatistiques" style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/consultation/informations-statistiques";?>" >
	       <img style="margin-left:5px; margin-top: -7px; width: 16px; height: 16px;" src='<?php echo $this->basePath().'/images_icons/statistics_16.png'?>' />
	       <span id="menu_statistiques_style" style="font-size:15px; color: white; font-family:Times New Roman;">Informations</span></a>
	   </div>
	   
	</li>
	
	
	
	
	
	
	
	
	
	
	
	
	<?php /*?>
	
	<!-- IMAGE *** Monsieur VCM *** -->
	<!-- IMAGE *** Monsieur VCM *** -->
	<li>
	
	<!-- Monsieur VCM -->
	<!-- Monsieur VCM -->
	
	   <div style="width: 90%; margin-left: 8px; margin-top: 40px; background: white; border: 1.5px solid #dcdcdc; box-shadow: 0 1px 2px rgba(0,0,0,0.3); border-radius: 10px;">
          <img style="border-radius: 10px;" src="http://localhost:5000/appliweb/vcm/mvcm/VCM:en_cours--hypo--globule_rouge.svg?scale=0.1&width=0&height=0" usemap="#imagemap" />
       </div>
       
       <map name="imagemap">
         <area onClick='hide_all();document.getElementById("fleche_anemie").style.display="block";document.getElementById("box_anemie").style.display="block"' shape="rect" coords="150, 80, 128, 45" title="anémie" />
       </map>
       
	   <div id="fleche_anemie" style='display:none; position:absolute; left:158px; top:101px; width:80px; border-top-style:solid; border-top-color:black; border-top-width:2px;'></div>
		
	   <div id="box_anemie" style='display:none; position:absolute; background-color:#FFFFBB; left:235px; top:71px; border-style:solid; border-color:black; border-width:1px; width: 520px;'>
	   <div onClick='hide_all()' style='float: right; border-right-style:none; border-top-style:none; border-bottom-style:solid; border-left-style:solid; border-color:black; border-width:1px; cursor:pointer;'> <b>&nbsp;X&nbsp;</b> </div>
	     <div style='margin:8px;'>
	       <b> Anémie </b>&nbsp;&nbsp;&nbsp;&nbsp;<br/> * Anémie régénérative hypochrome associée a une hyperleucocytose modérée. <span style='background-color: yellow; cursor: pointer;' onClick='ouvrirPopupResultat()'> &#128065; </span>
	     </div>
	   </div>

	   
	   

	   <script >
	   <!--
		if (typeof(window["hideables"]) == "undefined") {
		  hideables = new Array();
		}
		hideables.push('fleche_anemie');
		hideables.push('box_anemie');
		function hide_all() {
		  for(i = 0; i < hideables.length; i++) {
		    document.getElementById(hideables[i]).style.display="none";
		  }
		}

		function ouvrirPopupResultat() {
			hide_all();
			$('#antHistVCM, #histVCM, #analysesVCM, #resultAnalyseValideVCM').trigger('click');
		}
	   -->
	   </script>


	</li>

	<?php */ ?> 
	
	
	
	
</ul>


<?php
//CHOISIR LE MENU A AFFICHER SELON QUE C'EST LE MEDECIN OU LE SURVEILLANT
$user = $this->layout()->user;
$role = $user['role'];
?>


<script>

//*******************************************************************************************************************************
//*******************************************************************************************************************************
//CONSULTATIONS -- CONSULTATIONS
function dep_menu_consultation1(){
	$('#menu_consultations').click(function(){
		$("#menu_consultations").replaceWith("<li id='menu_consultations'><a style='cursor: pointer;'><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman; cursor: pointer;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Consultations </span></a></li>");
		dep_menu_consultation2();
	    $('#plus_menu_consultations').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_menu_consultation2(){
	$('#menu_consultations').click(function(){
		$("#menu_consultations").replaceWith("<li id='menu_consultations' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
		dep_menu_consultation1();
	    $('#plus_menu_consultations').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_menu_consultations').toggle(false);
$('#menu_consultations').click(function(){
	$("#menu_consultations").replaceWith("<li id='menu_consultations' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
	dep_menu_consultation1();
$('#plus_menu_consultations').animate({
height : 'toggle'
},1000);
return false;
});

//*******************************************************************************************************************************
//*******************************************************************************************************************************
//STATISTIQUES -- STATISTIQUES
function dep_menu_statistiques1(){
	$('#menu_statistiques').click(function(){
		$("#menu_statistiques").replaceWith("<li id='menu_statistiques'><a style='cursor: pointer;'><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman; cursor: pointer;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Statistiques </span></a></li>");
		dep_menu_statistiques2();
	    $('#plus_menu_statistiques').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_menu_statistiques2(){
	$('#menu_statistiques').click(function(){
		$("#menu_statistiques").replaceWith("<li id='menu_statistiques' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Statistiques </span></a></li>");
		dep_menu_statistiques1();
	    $('#plus_menu_statistiques').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_menu_statistiques').toggle(false);
$('#menu_statistiques').click(function(){
	$("#menu_statistiques").replaceWith("<li id='menu_statistiques' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Statistiques </span></a></li>");
	dep_menu_statistiques1();
$('#plus_menu_statistiques').animate({
height : 'toggle'
},1000);
return false;
});

</script>

